### DISCUSSION TITLE
Can this be used to sync JSON files by creating commits?

### DISCUSSION THREAD

**Discussion by zefir-git** [stefanzweifel/git-auto-commit-action#162] [Help] [answered]
I am new to GitHub actions. I am looking to create a workflow that would allow me the following:
1. The workflow is triggered by a commit on a file e.g. `/folder/a.json` (all properties are strings and all index:property pairs are on a new line)
2. If a line:
  a. is added: workflow inserts the same line in all other .json files in `/folder`
  b. is removed: workflow removes that line in all order .json files in `/folder`

I would really appreciate your help on this.

**Comment by stefanzweifel** [comment, marked as answer]
This should be possible. But `git-auto-commit` will only play a small role in that workflow.
`git-auto-commit` will only detect changes in files, commit them and push them pack to GitHub.

The logic that detects if a line has been added or removed and then updates a JSON file is up to you.


Here is a very basic example of how such a workflow could look like:

```yaml
name: Demo

on:
  push:
    paths:
      - 'folder/**.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Update JSON Files
        run: ./path/to/binary/to/run/your/logic

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Changed JSON Files
```
