### DISCUSSION TITLE
Passing variables to commit_message

### DISCUSSION THREAD

**Discussion by stevehillsTB** [stefanzweifel/git-auto-commit-action#182] [Help] [answered]
First, thank you for a really excellent action. I appreciate you!

I was wondering if there is a way to pass variables to the commit_message argument. I can't seem to resolve variables such as default environment variable '$GITHUB_RUN_NUMBER'. For example:

```yml
 - name: Commit Build Number
   uses: stefanzweifel/git-auto-commit-action@v4
   with:
     commit_message: Build Number ${GITHUB_RUN_NUMBER}
     file_pattern: version.h
```

Thanks.

Best Regards,
Steve

**Comment by stefanzweifel** [comment, marked as answer]
Hi Steve,

This should definitely be possible. 
I think this should be solvable by using [contexts](https://docs.github.com/en/actions/learn-github-actions/contexts).

Maybe a simple change like the one below works for you?

```yaml
- name: Commit Build Number
  uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: "Build Number $GITHUB_RUN_NUMBER"
    file_pattern: version.h
```

I've also found the following StackOverflow questions/answers that seem to e similar to what you want to achieve:

- https://stackoverflow.com/questions/60347162/github-actions-env-use-pre-defined-environment-variables-on-rhs-within-env-sec
- https://stackoverflow.com/questions/60432844/how-to-perform-string-manipulation-while-declaring-env-vars-in-github-actions

---

Just to clarify: `git-auto-commit` accepts any message for the commit message and is not responsible of what is allowed or how that message is built. That "logic" is part of GitHub Actions itself.

**Reply by stevehillsTB** [reply]
Thank you, @stefanzweifel !

Your answer is correct, using the context property github.run_number allowed the run number to be resolved correctly. 

```yaml
- name: Commit Build Number
  uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: Build Number ${{ github.run_number }}
    file_pattern: version.h

```

Best,
Steve
