### DISCUSSION TITLE
Will the new generated personal access token affect the workflow?

### DISCUSSION THREAD

**Discussion by edsml-yz1921** [stefanzweifel/git-auto-commit-action#184] [Help] [answered]
**Version of the Action**
`v4`

**Describe the bug**
GitHub noticed that my personal access token is going to expire. If I regenerate a new and equivalent token, will it affect the original functionality of the workflow?

**Expected behavior**
The workflow execute the python files to generate a new txt file and the action commits and pushes the new file to the repo. After updating the personal access token, new token does not affect the expected behavior.

**Used Workflow**

```yaml
# update timings.txt file and push back to the git repo.

name: update_timings_file

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run this workflow'

jobs:
  update_timings_file:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install -r requirements.txt

    - name: Run det_timings.py file
      run: |
        python3 scripts/det_timings.py
      continue-on-error: true
    
    - name: Git pull
      run: |
        git pull

    - name: Update the documents
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
          commit_message: Auto-generated timings.txt
```
