### DISCUSSION TITLE
Add tagging only on a specific branch

### DISCUSSION THREAD

**Discussion by nosisky** [stefanzweifel/git-auto-commit-action#208] [Help] [answered]
I would like to skip tagging for a specific branch, I don't know If there is an existing implementation for that. At the moment I have:

```
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message:  commit message
            tagging_message:  module version
            commit_user_name: Developer
            commit_user_email: developer@dev.com
```
            
   I would want something like:
   ```
          - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message:  commit message
            if branch === master
            tagging_message:  module version
            commit_user_name: Developer
            commit_user_email: developer@dev.com
    ```

**Comment by stefanzweifel** [comment, marked as answer]
This can be achieved in a couple of ways:

- By using the `on.pull_request.branches` trigger: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore
- By using `if`-conditions on the step block level. https://github.community/t/run-step-on-if-branch-tag-is/16965

In your example, it would look like this:

```yaml
       - uses: stefanzweifel/git-auto-commit-action@v4
       if: contains(github.ref, "master")
       with:
         commit_message:  commit message
         
         tagging_message:  module version
         commit_user_name: Developer
         commit_user_email: developer@dev.com
```
