### DISCUSSION TITLE
Commit same changes on multiple branches

### DISCUSSION THREAD

**Discussion by zaniluca** [stefanzweifel/git-auto-commit-action#221] [Help] [answered]
Hi! I was trying to figure out if it was possible to **commit the same changes that happened in the workflow to multiple branches**, my use case is pretty simple:

I have a workflow that builds and updates the `buildNumber` in a `.json` file during the process, I want to commit the changes to both my `production` and my `master` branch; the build only happens on push events on `production`

Right now my action does something like this:

```yml
      - name: Bump build and tag on master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "chore: bumped build numbers"
          commit_options: "--no-verify"
          tagging_message: "v${{steps.version.outputs.prop}}"
```
However, if I try to update both branches in sequence i get no commit from the second one (because there are no changes to commit, they were already committed on master!)
```yml
      - name: Bump build and tag on master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: "chore: bumped build numbers"
          commit_options: "--no-verify"
          tagging_message: "v${{steps.version.outputs.prop}}"

      - name: Bump build and tag on production
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: production
          commit_message: "chore: bumped build numbers"
          commit_options: "--no-verify"
          tagging_message: "v${{steps.version.outputs.prop}}"
```
Is there a git setting I'm not aware of I need to toggle to achieve this?
Thanks!
