### DISCUSSION TITLE
fatal: not a git repository (or any of the parent directories): .git

### DISCUSSION THREAD

**Discussion by NorkzYT** [stefanzweifel/git-auto-commit-action#224] [Help] [answered]
I would like to know how to fix this issue since I don't know what the local file path would be.

My `.yml`

```yml
name: git-auto-commit Action

on: [push]

#on:
  #schedule:
  #- cron: "0 2 * * 1-5"
  
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          # Optional. Commit message for the created commit.
          # Defaults to "Apply automatic changes"
          commit_message: Automated Change
          
          # Optional. Local and remote branch name where commit is going to be pushed
          #  to. Defaults to the current branch.
          #  You might need to set `create_branch: true` if the branch does not exist.
          #branch: main

          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'

          # Optional glob pattern of files which should be added to the commit
          # Defaults to all (.)
          # See the `pathspec`-documentation for git
          # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
          # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
          file_pattern: src/*.js tests/*.js *.php

          # Optional. Local file path to the repository.
          # Defaults to the root of the repository.
          repository: .
          
          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org# defaults to "github-actions[bot]@users.noreply.github.com"
          #commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          # Optional. Tag name being created in the local repository and 
          # pushed to remtoe repository and defined branch.
          tagging_message: 'v1.0.0'

          # Optional. Option used by `git-status` to determine if the repository is 
          # dirty. See https://git-scm.com/docs/git-status#_options
          status_options: '--untracked-files=no'

          # Optional. Options used by `git-add`.
          # See https://git-scm.com/docs/git-add#_options
          add_options: '-u'

          # Optional. Options used by `git-push`.
          # See https://git-scm.com/docs/git-push#_options
          #push_options: '--force'
    
          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true    
    
          # Optional. Skip internal call to `git fetch`
          skip_fetch: true    
    
          # Optional. Skip internal call to `git checkout`
          skip_checkout: true

          # Optional. Prevents the shell from expanding filenames. 
          # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
          disable_globbing: true

          # Optional. Create given branch name in local and remote repository.
          #create_branch: true
```

**Comment by stefanzweifel** [comment, marked as answer]
You don't clone a repository anywhere in your Workflow. Therefore there isn't any git repository when `git-auto-commit` is run.

It also looks like you've copied the extended example with all the options available in the Action. 
This example in the README acts more as a guide what's possible and not necessarily works out of the box.

Without knowing what exactly you want to accomplish and how your project structure looks like, I would suggest sticking to the bare minimum of options. And add a `actions/checkout` step at the beginning of a job.

It would look something like this:


```yaml
name: git-auto-commit Action

on: [push]

#on:
  #schedule:
  #- cron: "0 2 * * 1-5"
  
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Do something to change files
        run: |
          echo "Hello World" > file.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
```

See also [Example Workflow](https://github.com/stefanzweifel/git-auto-commit-action#example-workflow) in the README for details.
