### DISCUSSION TITLE
How do i disable the action from crediting me for every commit

### DISCUSSION THREAD

**Discussion by qfoxb** [stefanzweifel/git-auto-commit-action#243] [Help] [answered]
I've had trouble trying to get the action to stop mentioning me in every commit, it's adding to my daily commits and so It shows that i have multiple day even when i don't. Is there a way to turn this off? I've given the checkout action another account's personal access token and that didn't fix anything at all.

**Comment by stefanzweifel** [comment, marked as answer]
This can be changed by overriding the `commit_author` setting.

```yaml
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_author: GitHub Actions <actions@github.com>
```
