### DISCUSSION TITLE
Pushing to protected branch | --force not working

### DISCUSSION THREAD

**Discussion by nrl240** [stefanzweifel/git-auto-commit-action#249] [Help] [answered]
### Context
In two GitHub workflows (`push-to-staging` and `push-to-master`), I use `stefanzweifel/git-auto-commit-action@v4` to commit changes from updating a k8s image tag in my `deployment.yaml`. 
Recently, I added the following branch protection rules to `develop` (staging) and `master`:
![Protect-matching-branches](https://user-images.githubusercontent.com/26799918/195468204-fed91840-dff9-40d1-82ea-d20513b810bd.png)
![Rules-applied-to-everyone-including-administrators](https://user-images.githubusercontent.com/26799918/195468210-ba3fa526-5740-4510-93a0-9225f1a0fe09.png)

In adding those rules, I added the `'--force'` flag to the `push_options`. 
```yaml
- name: Commit changes to k8s manifest
  if: github.run_attempt == 1 # don't try to commit on re-runs
  uses: stefanzweifel/git-auto-commit-action@v4
  with:
      commit_message: Update container image
      tagging_message: 'k8s/${{ github.sha }}'
      file_pattern: k8s
      push_options: '--force'
``` 

### Issue/Error

Below is the error I'm seeing within the GitHub Action dashboard for that step:
```
remote: error: GH006: Protected branch update failed for refs/heads/develop.        
remote: error: 5 of 5 required status checks are expected.        
To https://github.com/MockCompany/some-app
 ! [remote rejected] develop -> develop (protected branch hook declined)
 ! [remote rejected] k8s/<some-hash>[68](https://github.com/MockCompany/some-app/actions/runs/xxxxxx/jobs/xxxxxx#step:8:69) <some-hash> -> k8s/<some-hash> (atomic transaction failed)
error: failed to push some refs to 'https://github.com/MockCompany/some-app'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```

### Would kindly love some advice, please.
