### DISCUSSION TITLE
disable workflow on protected branch

### DISCUSSION THREAD

**Discussion by gogo2464** [stefanzweifel/git-auto-commit-action#271] [Help] [answered]
accordoing to the doc: https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs I have to set the PAT to push  on protected branch.

Sadly it triggers workflow unexpectdly : https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs

What can I do to disable workflow on protected branch please?

Here is my workflow: https://github.com/gogo2464/cryptatools-rs/blob/master/.github/workflows/deploy-pypi-on-windows.yml#L44

**Comment by stefanzweifel** [comment, marked as answer]
If you're using a PAT you're responsible for guarding your workflows from unexpected runs.
For example, you can add a `if`-clause on the job level like this.

```yaml
name: Deploy

on:
    push:

jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        # Run this job if the commit message is not equal to "Change version with bump2version"
        if: github.event.head_commit.message != 'Change version with bump2version'
        steps:
            - run: # Deploy code

```

See:

- https://github.com/stefanzweifel/git-auto-commit-action/issues/237#issuecomment-1220428085
- https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif
- https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
