### DISCUSSION TITLE
How to write a multiline commit_message

### DISCUSSION THREAD

**Discussion by smallprogram** [stefanzweifel/git-auto-commit-action#279] [Help] [answered]
For example, I have a yml, similar to this form:
```yml
name: "test"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

       - name: Update 1
        run: |
          sed -i "8c PKG_VERSION:=1.1" Makefile
          cd
          echo "Version Update Title" >> commitmessage.txt

      - name: Update 1
        run: |
          sed -i "8c PKG_VERSION:=1.1" Makefile
          cd
          echo "Makefile version update 1.1" >> commitmessage.txt

      - name: Update 2
        run: |
          sed -i "12c PKG_VERSION:=1.2" Makefile
          cd
          echo "Makefile version update 1.2" >> commitmessage.txt

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: ./commitmessage.txt
          branch: packages   
```
Is it possible to put a multi-line commit message into a file, and then assign the content of this file to commit_message, so as to realize a multi-line commit message.

But I tried it, but it doesn't seem to work. Is there any way to achieve a multi-line commit message?

**Comment by stefanzweifel** [comment, marked as answer]
The value passed to `commit_message` must be a string. Actions isn't clever enough to see that you're referencing a file here.
I haven't tested the workflow below, but it should technically work:
(Added [a test](https://github.com/stefanzweifel/git-auto-commit-action/commit/fe00d258677e45d1f05473557e57bdfe865370fc) to cover this.)

```diff
name: "test"
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@main

       - name: Update 1
        run: |
          sed -i "8c PKG_VERSION:=1.1" Makefile
          cd
          echo "Version Update Title" >> commitmessage.txt

      - name: Update 1
        run: |
          sed -i "8c PKG_VERSION:=1.1" Makefile
          cd
          echo "Makefile version update 1.1" >> commitmessage.txt

      - name: Update 2
        run: |
          sed -i "12c PKG_VERSION:=1.2" Makefile
          cd
          echo "Makefile version update 1.2" >> commitmessage.txt

+     - name: Read Commit Message
+       id: commit_message_step
+       run: |
+         echo "commit_message=$(cat commitmessage.txt)" >> $GITHUB_OUTPUT;

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
-         commit_message: ./commitmessage.txt
+         commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
          branch: packages
```

The "Read Commit Message"-step outputs the value of `commitmessage.txt` and stores the value to a `commit_message` "variable" that can be referenced in the workflow later on.

The commit step is then updated to use the `commit_message`-value from the variable.

**Reply by smallprogram** [reply]
it's don't work...
```
Run cd && cd packages         
  cd && cd packages         
  echo "commit_message=$(cat commit_messages.txt)" >> $GITHUB_OUTPUT;
  shell: /usr/bin/bash -e {0}
  env:
    TZ: Asia/Shanghai
Error: Unable to process file command 'output' successfully.
Error: Invalid format 'brook: update to [2](https://github.com/smallprogram/openwrt-passwall/actions/runs/3862387214/jobs/6583924158#step:28:2)02[3](https://github.com/smallprogram/openwrt-passwall/actions/runs/3862387214/jobs/6583924158#step:28:3)0101'
```

https://github.com/smallprogram/openwrt-passwall/actions/runs/3862441589/jobs/6584014712

**Reply by smallprogram** [reply]
workflow code:

          cd && cd packages
          echo "xray-plugin: update to $New_PKG_VERSION" >> commit_messages.txt


      - name: Read Commit Message
        id: commit_message_step
        run: |
          cd && cd packages         
          echo "commit_message=$(cat commit_messages.txt)" >> $GITHUB_OUTPUT;

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
          branch: packages   

https://github.com/smallprogram/openwrt-passwall/blob/13d11c94de9897736978f3ce06c7a43026cfd0d9/.github/workflows/AUTO%20UPDATE%20PACKAGES%20PKG_VERSION%20AND%20PKG_HASH.yml#L396-L413

**Reply by stefanzweifel** [reply]
I'm not sure what the issue here is. From reading the GitHub Actions log it's not clear, where the error actually is. :(

`echo "{name}={value}" >> $GITHUB_OUTPUT` is the syntax to set output variables in GitHub Actions:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter


I've used this logic before in another project to extract the release date from a git tag. (`::set-output name={name}::value` syntax is deprecated, but the logic is the same as in my previous example)
https://github.com/stefanzweifel/git-auto-commit-action-demo-app/blob/main/.github/workflows/update-changelog.yml#L27

**Comment by smallprogram** [comment]
I try this:
```yml
- name: Read Commit Message
        id: commit_message_step
        run: |
          cd && cd packages
          cm=$(cat commit_messages.txt)
          cm="${cm//'%'/'%25'}"
          cm="${cm//$'\n'/'%0A'}"
          cm="${cm//$'\r'/'%0D'}"         
          echo -e "commit_message=$cm" >> $GITHUB_OUTPUT;
          echo $(cat commit_messages.txt)
```
but the commit message is this:
![image](https://user-images.githubusercontent.com/6050360/212457949-8ebf2cd1-e966-4c0b-badf-76b0832cf578.png)

after I try this:
```yml
      - name: Initialization environment
        run: |
          cd && mkdir -p packages && cd packages
          echo "<<EOF" >> commit_messages.txt
          echo "auto update packages" >> commit_messages.txt

      # some commit message code      

      - name: Read Commit Message
        id: commit_message_step
        run: |
          cd && cd packages
          echo "EOF" >> commit_messages.txt
          cm=$(cat commit_messages.txt)
          cm="${cm//'%'/'%25'}"
          cm="${cm//$'\n'/'%0A'}"
          cm="${cm//$'\r'/'%0D'}"         
          echo -e "commit_message=$cm" >> $GITHUB_OUTPUT;
          echo $(cat commit_messages.txt)
```
but the commit message is this:
![image](https://user-images.githubusercontent.com/6050360/212458062-0b7ab6a7-609b-4db1-b989-244edb24c0d8.png)

I want commit message like this:
![image](https://user-images.githubusercontent.com/6050360/212458114-928c6725-7c67-452b-b1a8-dcb84a222dae.png)


can anyone help me............................

**Reply by stefanzweifel** [reply]
I should have pointed you to the "Multiline Strings" parts of the GitHub Actions documentation one section above "Setting an output parameter".
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings

Apparently there is a custom syntax for multiline strings.

I've added the following steps to my example repo workflow.

```yaml
    # Building a multiline commit message
    # Adjust to your liking
    - run: echo "Commit Message 1" >> commitmessage.txt
    - run: echo "Commit Message 2" >> commitmessage.txt
    - run: echo "Commit Message 3" >> commitmessage.txt

    - name: Set commit message
      id: commit_message_step
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat commitmessage.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # Quick and dirty step to get rid of the temporary file holding the commit message
    - run: rm -rf commitmessage.txt

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
```

This is the [workflow run](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/actions/runs/3919331519/jobs/6700273389) and this is the resulting commit: https://github.com/stefanzweifel/git-auto-commit-action-demo-app/commit/82c2490337f04e711a2e809b1782a2b5d886e7a0

I think that's exactly what you want @smallprogram, right?

I will add an example to the README for multiline commits.

**Reply by smallprogram** [reply]
Thank you very much, this problem is solved. Thank you for your help

**Comment by Jason2866** [comment]
This is working for me with a used github actions. Probably this way will work here too
```
 - name: Build commit message
      id: step_one
      run: |
        tas_com_tmp1=$(curl https://raw.githubusercontent.com/arendst/Tasmota-firmware/action-development/trigger.txt)
        tas_com_tmp="Based on https://github.com/arendst/Tasmota/commit/${tas_com_tmp1}"
        echo "tas_com=$tas_com_tmp" >> $GITHUB_ENV
    - name: Display files to transfer
      run: ls -R ./*
    - name: Push Firmware files to tmp_copy repo
      uses: Jason2866/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'firmware'
        destination_repo: 'Jason2866/tmp_copy'
        destination_branch: 'firmware'
        user_email: 'github-actions@github.com'
        user_name: 'github-actions'
        commit_message: '${{ env.tas_com }}'
```
