### DISCUSSION TITLE
Diverging Paths when Auto-Committing in Parallel Jobs

### DISCUSSION THREAD

**Discussion by anerishah18** [stefanzweifel/git-auto-commit-action#290] [Help] [answered]
Hi,

I have a workflow with jobs like the following running in parallel:

```
jobs:
   job-1:
       steps:
           uses: actions/checkout@v3
           ...
           uses: stefanzweifel/git-auto-commit-action@v4
   job-2:
       steps:
           uses: actions/checkout@v3
           ...
           uses: stefanzweifel/git-auto-commit-action@v4
```

Say that job-1 finishes first. Trying to generate the auto-commit in job-2 says that the paths have diverged since job-1 already made a commit to the branch, making the branch checked out in job-2 behind the remote. I was wondering what the best way forward would be? I could make the auto-commit action force-push using the `push_options` config, but this would cause the changes from job-1 to be overwritten by the changes in job-2 even though the changes are not technically conflicting. Based on the searches I did, I couldn't really find a way to pull the latest branch before creating the auto-commit.
