### DISCUSSION TITLE
Keep workflow trigger after auto-commit on external contribution PR

### DISCUSSION THREAD

**Discussion by WarningImHack3r** [stefanzweifel/git-auto-commit-action#292] [Help] [answered]
I have a workflow that checks out the repo (with a `pull_request` trigger), makes some pre-checks and then execute the build step etc.

My issue is the following: for a PR I make on my repo from another branch, everything works fine and I have the intended behavior.   
However, when the workflow is triggered from an external member (dependabot or forks), the workflow cannot start because I use a `secrets.PAT` [as recommended in the README](https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs) to allow the workflow to be triggered from the new commits. This secret cannot be fetched from there for obvious security reasons on an unknown codebase.

A workaround could be to use the `pull_request_target` trigger, however in that case I can indeed access my secrets but the checkout would occur on _my_ `main` branch, which is not what I want.

To sum up, is there a way to keep a workflow triggered from the auto-commit without exposing secrets to an external contribution?

**Comment by stefanzweifel** [comment, marked as answer]
Hey

We have a dedicated section about how to setup the Action to run for forks of public repositories here: https://github.com/stefanzweifel/git-auto-commit-action#use-in-forks-from-public-repositories

In that workflow, there is no need for a PAT, if you don't use protected branches.
Could you give that a try?

Personal access token are ususally only needed if your repository uses protected branches or you must trigger another workflow run from commits made with this action.

If you must have secrets in your workflow and they need to be run for contributors, I actually don't know how to do that either. Would also need to do some research on this.

(In a personal project of mine, I also must [use secrets for an AWS account](https://github.com/stefanzweifel/sidecar-browsershot/blob/a758f2419931f8bb145a9754774fc0bc3dd9baba/.github/workflows/run-tests.yml#L68-L72) and I haven't figured out yet, how do make them safely available to contributors or dependabot. There is a special "Dependabot" section for secrets, but I don't think that works for contributors using public forks)

**Reply by WarningImHack3r** [reply]
Thanks for that! I didn't see it while reading the README, sorry.  
So actually what matters most is to check out the PR's repo, so the [first solution](https://github.com/stefanzweifel/git-auto-commit-action#workflow-should-run-in-base-repository) should do the trick just fine!

FYI:
- My `main` branch is indeed protected (not to allow direct push) but it shouldn't change anything I guess
- I don't use any other `secrets.*`

So yeah, I will try this first solution and update here if something doesn't work well. Thanks!

**Reply by WarningImHack3r** [reply]
Update @stefanzweifel: this setup will indeed work in forks because it doesn't use secrets anymore, but now the workflow isn't triggered anymore by the automatically pushed commit... What's your guess?
```yaml
jobs:
  myjob:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}
      
      ...

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update file
```
