### DISCUSSION TITLE
code 128 how to fix this

### DISCUSSION THREAD

**Discussion by dehydratoray** [stefanzweifel/git-auto-commit-action#296] [Help]
git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

**Comment by dehydratoray** [comment]
on:
  push:
    branches: ["main"]
    
permissions: write-all
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: install python packages
        run: |
          pip install PyGithub pandas
      - name: execute py script # run the run.py to get the latest data
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python generate_json.py -t ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: Automated Change
          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json bundleId.csv icons/*'

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          push_options: '--force'

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "update apps.json" -a
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.SECRET_NAME }}
      #     branch: main

**Reply by stefanzweifel** [reply]
Thank you for this very detailed report. 😐

I assume this workflow run caused you creating this discussion?
https://github.com/dehydratoray/Lootahmo/actions/runs/5738594719/job/15552506285#step:6:51

> fatal: You are not currently on a branch.

The `actions/checkout` Action will checkout your repository in a detached state when used using the scheduler trigger and when no branch or ref is provided.

Explicitly setting the `ref` should fix this issue.

```diff
on:
  push:
    branches: ["main"]
  release:
    types:
      - published
      - deleted
      - edited
      - prereleased
      - released
      - created
    
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
+       with:
+         ref: main
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8 #install the python needed
      - name: install python packages
        run: |
          pip install PyGithub pandas
      - name: execute py script # run the run.py to get the latest data
        env: 
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          python generate_json.py -t ${{ secrets.GITHUB_TOKEN }}
      - uses: stefanzweifel/git-auto-commit-action@v4
-       env: 
-         EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
-         EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
-         EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
-         GITHUB_TOKEN: ${{ github.token }}
        with:
          commit_message: Automated Change
          # Optional. Options used by `git-commit`.
          # See https://git-scm.com/docs/git-commit#_options
          commit_options: '--no-verify --signoff'
          file_pattern: 'apps.json bundleId.csv icons/*'

          # Optional commit user and author settings
          commit_user_name: My GitHub Actions Bot # defaults to "github-actions[bot]"
          commit_user_email: my-github-actions-bot@example.org # defaults to "41898282+github-actions[bot]@users.noreply.github.com"
          commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run

          push_options: '--force'

      # - name: commit files
      #   run: |
      #     git config --local user.email "action@github.com"
      #     git config --local user.name "GitHub Action"
      #     git add -A
      #     git commit -m "update apps.json" -a
          
      # - name: push changes
      #   uses: ad-m/github-push-action@v0.6.0
      #   with:
      #     github_token: ${{ secrets.SECRET_NAME }}
      #     branch: main
```

**Comment by nat-ray** [comment]
@stefanzweifel I am seeing a similar issue: 

```
on:
  workflow_call:

jobs:
  update_changelog:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: master

...

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          commit_message: Update CHANGELOG [skip ci]
          file_pattern: CHANGELOG.md 
```

Although a PAT and `ref` are specified, we get the following: 

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
##[debug]git binary found.
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
##[debug]Apply status options 
INPUT_FILE_PATTERN: CHANGELOG.md
INPUT_BRANCH value: 
M	CHANGELOG.md
INPUT_ADD_OPTIONS: 
##[debug]Apply add options 
INPUT_FILE_PATTERN: CHANGELOG.md
INPUT_COMMIT_OPTIONS: 
##[debug]Apply commit options 
INPUT_COMMIT_USER_NAME: github-actions[bot]
INPUT_COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
INPUT_COMMIT_MESSAGE: Update CHANGELOG [skip ci]
INPUT_COMMIT_AUTHOR: ...
[detached HEAD 7c9b92c] Update CHANGELOG [skip ci]
 Author: ...
 1 file changed, 7 insertions(+)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: --force
##[debug]Apply push options --force
##[debug]git push origin
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:[51](https://github.com/.../actions/runs/11374919082/job/31646989824#step:6:52)9:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```

Is there anything wrong with how the action is called?

**Reply by stefanzweifel** [reply]
@nat-ray At first glance I can't see a glaring problem. You checkout the repo to a specific branch using `ref` in `actions/checkout`, you don't set a `branch` in `git-auto-commit`; but the repo still ends up in a detached state.

> [detached HEAD 7c9b92c] Update CHANGELOG [skip ci]

> fatal: You are not currently on a branch.
> To push the history leading to the current (detached HEAD)
> state now, use
>  git push origin HEAD:<name-of-remote-branch>

Do any of the intermediary steps change the branch of the checked out repo?

**Reply by nat-ray** [reply]
> Do any of the intermediary steps change the branch of the checked out repo?

@stefanzweifel Not that I know of. The entire workflow yaml is very simple: 

```
name: Update Changelog

on:
  workflow_call:

jobs:
  update_changelog:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          ref: master

      - name: Format release date
        id: release_date
        run: echo "slash_date=$(date +'%m/%d/%Y')" >> $GITHUB_OUTPUT
      - name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1
        with:
          release-date: (${{ steps.release_date.outputs.slash_date }})
          release-notes: ${{ github.event.release.body }}
          latest-version: ${{ github.event.release.tag_name }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: --force
          commit_message: Update CHANGELOG [skip ci]
          file_pattern: CHANGELOG.md
```
