### DISCUSSION TITLE
Error with Action

### DISCUSSION THREAD

**Discussion by olebohmbach** [stefanzweifel/git-auto-commit-action#299] [Help] [answered]
With the following Code:

```yaml
name: Auto Minify and Commit

on:
  push:
    branches:
      - main # Ändern Sie dies entsprechend dem Hauptzweig Ihrer Repository-Struktur

jobs:
  minify_and_commit:
    runs-on: ubuntu-latest

    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so the auto-minify job can access it
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Erstelle das 'output'-Verzeichnis
      - name: Erstelle das 'output'-Verzeichnis
        run: mkdir -p output

      # Kopieren Sie das 'app'-Verzeichnis in das 'output'-Verzeichnis
      - name: Kopieren Sie 'app' in 'output'
        run: cp -r app/* output/

      # Auto Minify JS
      - name: Auto Minify JS
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'output/js'  # Minifizieren Sie JavaScript-Dateien im 'app/js'-Verzeichnis
          overwrite: true       # Hinzufügen der Option 'overwrite: true' (überschreiben Sie die vorhandenen Dateien)

      # Auto Minify CSS
      - name: Auto Minify CSS
        uses: nizarmah/auto-minify@v2.1
        with:
          directory: 'output/css'  # Minifizieren Sie CSS-Dateien im 'app/css'-Verzeichnis
          overwrite: true       # Hinzufügen der Option 'overwrite: true' (überschreiben Sie die vorhandenen Dateien)

      # Auto commit minified files to the repository
      - name: Auto Commit Minified Files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          repository: ${{ github.repository }}
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: ${{ github.ref }}

```

I get this Error:

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: olebohmbach/ashampoo-template-string-builder
/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh: line 75: cd: olebohmbach/ashampoo-template-string-builder: No such file or directory
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:[16](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:17))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:[17](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:18):[19](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:20))
    at ChildProcess.emit (node:events:5[27](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:28):[28](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:29))
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:[30](https://github.com/olebohmbach/ashampoo-template-string-builder/actions/runs/5918303021/job/16047489264#step:8:31)2:5)
```
