### DISCUSSION TITLE
Unable to push modifications made in the main branch to another branch

### DISCUSSION THREAD

**Discussion by DawidNiezgodka** [stefanzweifel/git-auto-commit-action#301] [Help] [answered]
I have the following scenario: My repository contains two branches, `main` and `bench_data`. The `main` branch houses the logic of a JavaScript-based GitHub Action, while the `bench_data` branch serves as the repository for the current version of the `data.json` file.

In my workflow, I initially check out the `main` branch and then proceed to check out the `bench_data` branch. The `bench_data` branch is checked out into a distinct folder. Let's assume that within the primary logic of my action, there exists a function that reads `data.json` from the folder where `bench_data` was checked out, applies certain modifications to it, and subsequently saves the updated version of the file (i.e., the content from the `folder_where_bench_data_is_stored/data.json` along with some new changes) as `data.json` in the root directory. My objective is to push the newly generated `data.json` to the `bench_data` branch. Regrettably, I encounter the following error:

```
From https://github.com/DawidNiezgodka
 * [new branch]      bench_data -> origin/bench_data
error: Your local changes to the following files would be overwritten by checkout:
	data.json
Please commit your changes or stash them before you switch branches.
Aborting
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

Here's the complete workflow:
```
name: "test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout the main branch
      uses: actions/checkout@v3

    - name: checkout the bench_data branch to a given folder
      uses: actions/checkout@v3
      with:
        ref: 'bench_data'
        sparse-checkout: |
          data.json
        sparse-checkout-cone-mode: false
        path: 'benchmark_data'

    - name: print the content of the file from the bench_data branch
      run: cat benchmark_data/data.json

    - name: evaluate benchmark (the modification of data.json takes place within this action)
      uses: ./
      with:
        input1: ...

    - name: print the content of the data file after the update
      run: cat data.json

    - name: push the updated data file to the bench_data branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: bench_data
        file_pattern: 'data.json'
        create_branch: false
        push_options: '--force'
```

Could you please help me modify the usage of action `stefanzweifel/git-auto-commit-action@v4` so that I can place a new version of `data.json` in branch `bench_data`?
Alternatively, what steps need to be taken apart from using the action itself to achieve this goal?
