### DISCUSSION TITLE
How can I make it so that no one would be authored?

### DISCUSSION THREAD

**Discussion by VasilisThePikachu** [stefanzweifel/git-auto-commit-action#303] [Help] [answered]
For my purpose, this will be used weekly automatically to update a "credits" file

Since this will be automatic, there's no reason for it to co-author people. It just looks ugly especially if it co-authors an unrelated committer

Any way to just remove this?

```yml
name: Update Contrib and Patreons in credits

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0
    
jobs:
  get_credits:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.6.0
        with:
          ref: master
        
      - name: Get this week's Contributors
        shell: pwsh
        run: Tools/dump_github_contributors.ps1 > Resources/Credits/GitHub.txt
        
      #- name: Get this week's Patreons
      #  shell: pwsh
      #  run: Tools/patreonscripthere.amog > Resources/Credits/Patrons.yml
        
      - name: Commit new credit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Credits
          commit_author: # My attempt to make it empty here...
          branch: actiontest
          create_branch: true
```

My other option is to coauthor one of our bot's but I'm not really into that idea

**Comment by stefanzweifel** [comment]
Hi there.

I haven't tested this, but you could set the `commit_user_name` and `commit_user_email` options to values related to the user that triggered the workflow.

```diff
 -  name: Commit new credit files
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
        commit_message: Update Credits
        commit_author: # My attempt to make it empty here...
+       commit_user_name: ${{ github.actor }}
+       commit_user_email: ${{ github.actor }}@users.noreply.github.com
        branch: actiontest
        create_branch: true
```

For context, git-auto-commit currently hard codes these values to `github-actions[bot]` and `41898282+github-actions[bot]@users.noreply.github.com`, so that the commit looks like it has been Co-Authored by GitHub Actions.

---

> It just looks ugly especially if it co-authors an unrelated committer.

I would like to understand better, why you think this looks _ugly_. 

You're not the first one to mention that they don't like that commits are co-authored by Github Actions. I've added this feature to the Action as I wanted to highlight to others, that this commit wasn't made by a human, but by a bot.

**Reply by VasilisThePikachu** [reply]
Well ugly may have been a bit of a overstatement. I just think a contribution by "GitHub actions" could convey enough that this is an automatic contribution. Now yes I would love this if this was used in pr's/after commit etc. But with my current setup where it's on a schedule it just looks a little wierd for it to pick up the latest commiter.

As for the suggestion thanks! I will try it and get back to you

**Reply by AidanWelch** [reply]
I'm confused, do you know why it could be including an author even when an empty string is passed?

```
INPUT_ADD_OPTIONS: 
INPUT_FILE_PATTERN: cameras/*.json
INPUT_COMMIT_OPTIONS: 
INPUT_COMMIT_USER_NAME: github-actions[bot]
INPUT_COMMIT_USER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
INPUT_COMMIT_MESSAGE: Daily Camera Update
INPUT_COMMIT_AUTHOR: 
[master 29aaed0] Daily Camera Update
 Author: Aidan Welch <aidan@freedwave.com>
 1 file changed, 1 insertion(+), 1 deletion(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
```

**Reply by stefanzweifel** [reply]
@AidanWelch Can you share the exact workflow step?

My guess is that GitHub Actions falls back to our default value here:
https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml#L46

**Reply by AidanWelch** [reply]
Here

```yml
name: collate

on:
  workflow_dispatch:
  schedule:
  - cron: '0 0 * * *'

jobs:
  collate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: npm ci
    - name: Install OpenVPN
      run: |
        sudo apt update
        sudo apt install -y openvpn openvpn-systemd-resolved
    - name: OpenVPN-Connect
      uses: kota65535/github-openvpn-connect-action@v2.1.0
      with:
        config_file: .github/workflows/us_east.ovpn
        username: ${{ secrets.PIA_USERNAME }}
        password: ${{ secrets.PIA_PASSWORD }}
    - run: npm run start
    - name: Commit cameras
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Daily Camera Update
        commit_author: ''
        file_pattern: 'cameras/*.json'
```
Also thanks for the quick response!
I also tried with an empty commit_author instead of `''`

**Reply by AidanWelch** [reply]
@stefanzweifel I just wanted to bump this

**Reply by stefanzweifel** [reply]
As mentioned in the previous comment, I assume that an empty value will be ignored and that GitHub Action will fall back to the default we've declared in `action.yml`.

Did you try using `github.actor`?
https://github.com/stefanzweifel/git-auto-commit-action/discussions/303#discussioncomment-7061461

As I don't know what you want (always commit as the user or as a bot) I can only link to our [`action.yml`](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml#L35-L46).

There you can see how the default values are generated. Depending on what you want to achieve, you have to copy & paste the respective values to your workflow.

**Reply by AidanWelch** [reply, marked as answer]
@stefanzweifel 

Actually that was exactly what I was looking for! This:

```yaml
    - name: Commit cameras
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Daily Camera Update
        commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        file_pattern: 'cameras/*.json'
```

So it doesn't add a user as an author
