### DISCUSSION TITLE
New commit randomly does not trigger a new workflow run

### DISCUSSION THREAD

**Discussion by canvural** [stefanzweifel/git-auto-commit-action#313] [Help]
Hi,

My issue is two fold.

I'm checking out the repo with a personal token, so that I can push back the commit and trigger new workflow runs. Like so
```yaml
- name: Checkout
  uses: actions/checkout@v4
  with:
    token: ${{ steps.generate_token.outputs.token }}
```

This works correctly, and when this action pushes new commit a new workflow runs and because of the concurrency settings Github Actions cancels the current workflow. All good.

But the above snippet results in a detached head state. This later causes some issues. So I modified the script like so:
```yaml
- name: Checkout
  uses: actions/checkout@v4
  with:
    token: ${{ steps.generate_token.outputs.token }}
    ref: ${{ github.event.pull_request.head.ref }}
```
 so that it'll checkout the branch correctly. No more detached head states.

But this brings out another issue. When I check out the repo like this, a new commit with this action does not trigger a new workflow run 🤯 But also it seems random, because in some cases it did trigger a new run 🤷🏽 

Did anybody have this kind of issue before? I'm not sure where the problem is though. This action or `actions/checkout` I also tried:
- checking out the repo with `ref: ${{ github.ref }}`
- checking out the repo with `ref: ${{ github.head_ref }}`

still same issue.

**Comment by stefanzweifel** [comment]
When the Action fails to trigger another workflow, are the commits going to the right branch?
Maybe adding an explicit `branch`-setting can help here.

```yml
- uses: stefanzweifel/git-auto-commit-action@v5
  with:
    branch: ${{ github.event.pull_request.head.ref }}
```

Or are you working with forks? Do those rogue commits go the fork-repo?
