### DISCUSSION TITLE
Multiple commit author

### DISCUSSION THREAD

**Discussion by ben1one** [stefanzweifel/git-auto-commit-action#320] [Help]
Now the commit author is set to my name and github action [bot].
How can I remove myself and make github action [bot] the only author to the auto commit?

**Comment by stefanzweifel** [comment]
@ben1one Update your workflow to pass a custom `commit_author` to the Action. The follow code snippet reuses the [`commit_user_*`-values](https://github.com/stefanzweifel/git-auto-commit-action/blob/4d160c5e4d67c62e67f03ae49aa38359e964139a/action.yml#L35-L42) for the commit_author as well.

```yml
- uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
```
