### DISCUSSION TITLE
Include action url in commit message

### DISCUSSION THREAD

**Discussion by hadley** [stefanzweifel/git-auto-commit-action#333] [Help] [answered]
It would be super useful to include the url to the summary page of the current action in the commit message so you could more easily jump to the log.

**Comment by stefanzweifel** [comment, marked as answer]
Sorry only saw this discussion today.

You're suggesting that the commit message created by git-auto-commit automatically adds a link to the "run"-page where the commit has been created from, to the commit body, right?

So instead of a commit log that would look like this:

```
commit 4593f3c90f7d97682e4e615849d48a8991ffabc859579e8a3921f1647f5ad340
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   2024-07-06 12:06:47 +0200

    Apply automatic changes
```

It would look like this:

```
commit 4593f3c90f7d97682e4e615849d48a8991ffabc859579e8a3921f1647f5ad340
Author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Date:   2024-07-06 12:06:47 +0200

    Apply automatic changes

    https://github.com/stefanzweifel/git-auto-commit-action/actions/runs/9818457191
```

I think this is not something I would like to add to the action itself. I currently can't see the benefit of adding this to all commits made with this action.

However, you're able to do this yourself by reading the [`GITHUB_RUN_ID`](https://docs.github.com/de/actions/learn-github-actions/variables)-variable and using it in a [multiline commit mesage](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#multiline-commit-messages).

I haven't tested this exact workflow, but this is how you could add a link to the workflow run to the body of your commit.

```yml
    # Building a multiline commit message
    # Adjust to your liking
    - run: echo "Apply automatic changes" >> commitmessage.txt
    - run: echo "https://github.com/your-org/your-repo/actions/runs/$GITHUB_RUN_ID" >> commitmessage.txt

    # Create a multiline string to be used by the git-auto-commit Action
    - name: Set commit message
      id: commit_message_step
      run: |
        echo 'commit_message<<EOF' >> $GITHUB_OUTPUT
        cat commitmessage.txt >> $GITHUB_OUTPUT
        echo 'EOF' >> $GITHUB_OUTPUT

    # Quick and dirty step to get rid of the temporary file holding the commit message
    - run: rm -rf commitmessage.txt

    - uses: stefanzweifel/git-auto-commit-action@v5
      id: commit
      with:
        commit_message: ${{ steps.commit_message_step.outputs.commit_message }}
```
