### DISCUSSION TITLE
Why `git-auto-commit-action` does not consider my all git history?

### DISCUSSION THREAD

**Discussion by charnould** [stefanzweifel/git-auto-commit-action#340] [Help] [answered]
Hello,
First, thanks for making this GH action; it's a life/time-saver :-). 
However, and I'm a `git-auto-commit-action` newbie, I have an issue/problem.

Consider this GH action:

```
name: Build changelog

on:
  push:
    branches:
      - master

jobs:
  run-braudel:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun build:changelog

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: auto-generate changelog'
          commit_user_name: robot
```

I'm totally able to auto-commit on `push`; this is perfect BUT:

- why does author keep being `github-actions[bot]` and not `bot`
- but my main issue is:  
  `bun build:changelog` (similar to `npx build:changelog`) just runs an `npm` script generating a changelog of **all** my commit history. When I run this script locally, it outputs my all commit history (OK), but when I do it via my GH action, it prints/outputs/writes only my LAST commit (NOT OK).

Do you know what's happening?

Thanks for your guidance!

**Comment by stefanzweifel** [comment]
Hi!

> why does author keep being github-actions[bot] and not bot

"github-actions[bot]" is [the default `commit_user_name`](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/action.yml#L35-L38) I've used when I launched this project. 
The idea was to showcase, that the commit was made by a bot and that the commit was made through GitHub Actions. When I remember correctly, I think this was the same _schema_ how Dependabot made commits.

As you might already noticed, you can change that by passing a different string to `commit_user_name`.

To your main issue: This is related to [`actions/checkout`](https://github.com/actions/checkout). By default, only a single commit is fetched. If you want the entire history of the repository available during a Actions run, you have to pass `fetch-depth: 0` to that step.

You workflow should then look like this:

```yml
name: Build changelog

on:
  push:
    branches:
      - master

jobs:
  run-braudel:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun build:changelog

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: auto-generate changelog'
          commit_user_name: robot
```

**Reply by charnould** [reply]
it works like a charm for `fetch-depth: 0`; thanks. 
However bot's name still is `github-actions[bot]`, weird.... any clue?
Thanks again!

![Capture d’écran 2024-08-28 à 17 11 23](https://github.com/user-attachments/assets/a261401f-c669-4aa6-aba8-e46cfa80a5ce)

**Reply by stefanzweifel** [reply, marked as answer]
@charnould It looks like the commit_user_email takes presedence when GitHub deploys the commit user information.
https://github.com/charnould/pierre/actions/runs/10599613904/job/29375069889#step:6:27

Adding a different email address in `commit_user_email` should fix that.

```yml
name: Build changelog

on:
  push:
    branches:
      - master

jobs:
  run-braudel:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: oven-sh/setup-bun@v2
      - run: bun build:changelog

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'docs: auto-generate changelog'
          commit_user_name: robot
          commit_user_email: robot@example.com
```
