### DISCUSSION TITLE
Github workflows don't run on auto-commit

### DISCUSSION THREAD

**Discussion by salahhusa9** [stefanzweifel/git-auto-commit-action#341] [Help] [answered]
### Using:
```yml
      - name: Commit linted files
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Fixes coding style"
```

### Problem:
i want to run some github workflows on commit from your github action, this workflows run in my commit but don't run in your commits, why? and how fix?

![Screenshot_31-8-2024_121826_github com](https://github.com/user-attachments/assets/64da0059-f71d-4996-b306-25325a9705c9)
