### DISCUSSION TITLE
Commit & push work fine on a manual Run workflow but not on a cron scheduled one

### DISCUSSION THREAD

**Discussion by Kamal-Moha** [stefanzweifel/git-auto-commit-action#349] [Help] [answered]
Hi I'm trying to create a github actions that runs on a cron scheduled time and use the git-auto-commit to handle the commit & push. 
I'm facing the issue whereby git-auto-commit is working fine for manual run workflow and actually pushing changes to repo, but it doesn't work as expected with the cron scheduled.

Below is my yml file

```yml
name: Data Collection & Sync

on:
  workflow_dispatch:
  
  schedule:
    - cron: "11 17 * * *" # Run everyday at 17:11

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # checkout the repository content to github runner
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r actions_requirements.txt
          
      - name: execute py script # run main.py
        env:
          AUTH_KEY: ${{ secrets.AUTH_KEY }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          python wallet_accts.py 
          python acct_df.py 
      
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Synced data from API'
```

When I manually run this workflow, it works perfectly. But when the cron scheduled action runs, I get the below error;
`Working tree clean. Nothing to commit.`

![image](https://github.com/user-attachments/assets/757083d4-0720-44d1-a8f8-8b13794a640e)

Please help
