### DISCUSSION TITLE
Commiting from Azure Repos

### DISCUSSION THREAD

**Discussion by FinishingLine** [stefanzweifel/git-auto-commit-action#350] [Help]
Seem to be struggling getting a commit working from Azure Repos (AR) to get this commited in Github (GH) - probably doing something stupid

From AR pipeline, I'm cloning the GH repo; moving files + directories that I need to keep; then adding files that have been generated with my AR pipeline process; then commiting it, adding a tag, then pushing it to GH

```
git clone https://%PAT%@github.com/xxx/yyy.git yyy

copy yyy\index.md docs\index.md /y

rmdir yyy /s /q

xcopy docs\subdir\* yyy\subdir\ /s /i /r /y
copy docs\index.md yyy\

cd yyy

git config user.email "abc@def.co.uk"
git config user.name "Service Account"

git add subdir

git commit -a -m "Docs Update"
git tag v%BUILDVERSION%
git push --force --tags --set-upstream https://%PAT%@github.com/xxx/yyy.git
```

Then within the GH action where hopefully it creates a branch to put the commit that comes through onto

```
on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: "docs/update"
          create_branch: true
          commit_message: "Docs Update"
          tagging_message: "${{ github.ref_name }}"
          push_options: '--force'
```

Everything seems to work fine, but keep getting the below

```
Working tree clean. Nothing to commit.
```

My guess is that the push isn't quite right or missing something in checkout? The files have 100% come across as I can see them under the tag within GH, complete with the changes - so not sure what needs tweaking
