### DISCUSSION TITLE
Help with gitignore

### DISCUSSION THREAD

**Discussion by vincerubinetti** [stefanzweifel/git-auto-commit-action#351] [Help] [answered]
I have a repo structure that looks like this

```
/_cite/.cache/some-junk-abc123
/_cite/.cache/cache.db
/_cite/.cache/more-junk-abc123
```

I want to keep the `cache.db` file in git, but not the other stuff in that folder. Following the advice of [this stackoverflow post](https://stackoverflow.com/questions/987142/make-gitignore-ignore-everything-except-a-few-files), my `.gitignore` looks like this:

```
.cache
!cache.db
```

My workflow that tries to commit this `cache.db` file looks like:

```yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: _cite/.cache/cache.db
          commit_message: "Commit cache"
```

But I get the error:

```
INPUT_FILE_PATTERN: _cite/.cache/cache.db
The following paths are ignored by one of your .gitignore files:
_cite/.cache
hint: Use -f if you really want to add them.
hint: Disable this message with "git config advice.addIgnoredFile false"
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/index.js:17:19)
```

This is probably more of a git question than a question specifically with this action. But perhaps it has to do with the specific git commands called in this action, because locally, my gitignore pattern seems to correctly add/ignore the proper files, and never throws such an error when adding/committing/pushing.

Any ideas, besides using the "force" flag as it suggests? Could the `disable_globbing` flag be relevant?
