### DISCUSSION TITLE
Option to skip pre-commit hooks

### DISCUSSION THREAD

**Discussion by ryanwilsonperkin** [stefanzweifel/git-auto-commit-action#352] [Help] [answered]
It would be useful to have an option to run this action in a way that uses git's `--no-verify` flag to skip hooks for things like pre-commit. I help maintain a repo that has pre-commit hooks installed by [Husky](https://www.npmjs.com/package/husky) during the installation stage, as we want them enforced for developer environments, but would prefer to skip them in CI actions.

**Comment by stefanzweifel** [comment, marked as answer]
There's a [`commit_options`-input](https://github.com/stefanzweifel/git-auto-commit-action?tab=readme-ov-file#usage) available.
If you want to pass `--no-verify` to `git-commit`, you can update you workflow like this:

```yml
- uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_options: '--no-verify'
```

I think that should solve the problem with the pre-commit hooks.
