### DISCUSSION TITLE
GitHub Action Timing Out

### DISCUSSION THREAD

**Discussion by souvikinator** [stefanzweifel/git-auto-commit-action#358] [Help]
We are experiencing a timeout issue when using git-auto-commit-action@v5 in our GitHub Actions workflow. The action runs indefinitely until it exceeds the time limit. Other steps in the workflow are completed, and only this action appears to be affected. 

Suspect is large number of files being committed however I'm not sure what's the expected behaviour.

**Current workflow configuration:**

```yml
- name: Commit changes
  uses: stefanzweifel/git-auto-commit-action@v5
  with:
    commit_user_name: [redacted]
    commit_user_email: [redacted]
    commit_options: "--signoff"
    commit_message: "New Models generated and updated"
    branch: master
```

![Image](https://github.com/user-attachments/assets/34ebed53-4c6c-4976-ad26-2968ef6c48c9)

Link to one of the failing runs: https://github.com/meshery/meshery/actions/runs/13253120994/job/36995032146

Any insights or suggestions would be greatly appreciated. Thanks!
