### DISCUSSION TITLE
Commiting gitignored files

### DISCUSSION THREAD

**Discussion by rlipperts** [stefanzweifel/git-auto-commit-action#362] [Help] [answered]
I am trying to write a github action that builds my latex file and commits it to a separate branch. The building (and uploading as an artifact) work so far, but when trying to use the commit action i cannot get it to actually add the file (but i did add the --force option to git add).

This is my Action Code:
```
name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
        # Give the default GITHUB_TOKEN write permission to commit and push the
        # added or changed files to the repository.
        contents: write
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: thesis.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: thesis.pdf
      - name: Commit and push pdf to pdf-storage branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: update doc pdf file
          file_pattern: 'thesis.pdf'
          branch: pdf-storage
          add_options: '--force'
          push_options: '--force'
```

And this is the output of the execution:
```
Run stefanzweifel/git-auto-commit-action@v5
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v5/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: thesis.pdf
Working tree clean. Nothing to commit.
```

Did i miss something? By adding the force-option to git-add the file should be used even if it would otherwise be ignored by the .gitignore.
And i have made sure that the thesis.pdf file is actually created in the prior steps.
