### DISCUSSION TITLE
Option to `--unshallow` before committing

### DISCUSSION THREAD

**Discussion by rhys-vdw** [stefanzweifel/git-auto-commit-action#365] [Ideas]
Firstly, loving the tool, thanks :-)

I'd like an option to unshallow a repo before merging.

[Workflow in question](https://github.com/beyond-all-reason/Beyond-All-Reason/blob/112681b4c030ff75ddc543174fc49fb7aa2553b7/.github/workflows/update-recoil-lua-library.yml)

If we remove the `fetch-depth: 0` here we get a shallow checkout (which is desirable, this repo is >3GB), but the downside is that [we can't merge back into master due to](https://stackoverflow.com/questions/74266133/git-unable-to-merge-unrelated-histories-shallow-clone):

> fatal: refusing to merge unrelated histories

So, the ideal behaviour here is:

1. Check out shallow.
2. Make any changes
3. _if_ there are changes
   1. do a `git fetch --unshallow`
   2. then merge

So I could add a dirty check and unshallow as a different step. But, because `git-auto-commit-action` handles the dirty check, it would be very convenient to have an option like:

```yaml
      - name: Push updated submodule
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: recoil-lua-library
          unshallow: true
          commit_message: |
            Update Lua libary submodule
```
