### DISCUSSION TITLE
How to reformat and commit the code on apache repositories if we could not grant GITHUB_TOKEN write permission?

### DISCUSSION THREAD

**Discussion by zrlw** [stefanzweifel/git-auto-commit-action#372] [Help] [answered]
i want reformat the codes with ```mvn spotless:apply``` and commit the code changes by ```git-auto-commit-action``` through ```build-and-test-pr.yml```:
```
name: "Build and Test For PR"
on: [push, pull_request, workflow_dispatch]
permissions:
   // Give the default GITHUB_TOKEN write permission to commit the changed files back to the repository. 
  contents: write

jobs:
  reformat-and-commit:
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: "Setup maven"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
      - name: "Reformat code by using spotless:apply"
        id: apply
        run: mvn --log-file spotless.log spotless:apply
        continue-on-error: true
      - name: "Commit reformated code"
        id: commit
        if: ${{ steps.apply.outcome == 'success' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply reformated code"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
```
but one admin of apache repositories told me that the GITHUB_TOKEN write permission could not be granted on all apache repos, it seemed that ```git-auto-commit-action``` could not commit the code changes without the write permission.
so how to reformat and commit the code on apache repos?
