### DISCUSSION TITLE
Trigger pipeline

### DISCUSSION THREAD

**Discussion by ghost** [stefanzweifel/git-auto-commit-action#374] [Help] [answered]
I have the issue, that after I commit a message with this action, it will not trigger the pipeline.

Here are the relevant parts of my yaml file.

```yaml
name: Documentation
run-name: Checking ${{ github.actor }}'s documentation files

on:
  pull_request:
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

  fix-formatting:
    needs: check-formatting
    runs-on: ubuntu-latest
    name: Fix Formatting

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

     ...

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          id: auto-commit-action
          commit_message: "ci: fix LaTeX formatting"
```

So as mentioned, this will create a commit with the fixed files, but the new commit will not trigger the pipeline.
