### ISSUE TITLE
[remote rejected] test -> test (shallow update not allowed)

### ISSUE THREAD

**Issue by rimonhanna** [stefanzweifel/git-auto-commit-action#102]
**Version of the Action**
`v4.x.x

**Describe the bug**
Only once in a while from a workflow triggered by a cron job I get this error:

```
1 file changed, 1 insertion(+)
INPUT_TAGGING_MESSAGE: 
 No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: --force

! [remote rejected] test -> test (shallow update not allowed)
error: failed to push some refs to 'https://github.com/Eyvit/EyvitSalesforce'
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.5.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
```

**To Reproduce**

**Expected behavior**
Action should commit the files successfully

**Screenshots**
NA

**Used Workflow**

**yaml**

``` 
on:
    workflow_dispatch:
    schedule:
        - cron: '*/30 0-4/1 * * 1-5' # Every Week Day from 2-6AM every 60 minutes

jobs:
    create-scratch-orgs:
        name: Batch Create Scratch Orgs
        runs-on: ubuntu-latest
        steps:

           - name: 'Checkout source code'
              uses: actions/checkout@v2
              with:
                  ref: 'test'
                  token: ${{ secrets.ACTIONS_ACESS_TOKEN }}

           - name: 'Commit updated scratch-orgs.txt to repo'
              uses: stefanzweifel/git-auto-commit-action@v4.5.1
              with:
                  commit_message: 'Created a new scratch org'
                  file_pattern: scratch-orgs.txt
                  push_options: '--force'
```
