### ISSUE TITLE
Nothing to commit but changes_detected output still set to true

### ISSUE THREAD

**Issue by ondrejmirtes** [stefanzweifel/git-auto-commit-action#104]
**Version of the Action**
`stefanzweifel/git-auto-commit-action@v4`

**Describe the bug**

I want to tag a new version and create a release only when some changes are commited by this action.

**To Reproduce**

This is how my workflow looks like:

```yml
      - name: "Commit changes"
        uses: "stefanzweifel/git-auto-commit-action@v4"
        id: "commit"
        with:
          commit_message: "Update stubs"
          commit_user_name: phpstan
          commit_user_email: actions@github.com
          commit_author: PHPStan Bot <actions@github.com>
      - name: "Tag new version"
        if: ${{ steps.commit.outputs.changes_detected }} == "true"
        id: "tag"
        uses: "anothrNick/github-tag-action@1.30.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false
          RELEASE_BRANCHES: main
          DEFAULT_BUMP: patch
      - name: "Release new version"
        if: ${{ steps.commit.outputs.changes_detected }} == "true"
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: ${{ steps.tag.outputs.new_tag }}
          commitish: main
          body: "Update stubs"
```

The problem is that `"Tag new version"` and `"Release new version"` are executed even when this action outputs `Working tree clean. Nothing to commit.` and nothing is commited.

Here it can be seen in practice: https://github.com/phpstan/php-8-stubs/runs/1208734008?check_suite_focus=true

Thank you.
