### ISSUE TITLE
Checkout new commit after auto-commit

### ISSUE THREAD

**Issue by Aebrathia** [stefanzweifel/git-auto-commit-action#105]
Hi,

I have a workflow with 2 jobs. I would like to commit some changes in a first job and checkout the new commit in a second job. By default the second checkout uses the workflow ref. Thus, I need to specify a ref but I have yet to find how to specify the ref that always match git-auto-commit. 

git-auto-commit's default branch is `${{ github.head_ref }}`. But in my example below, in case of a manual workflow_dispatch the value of the head_ref is `''`.

Is there a way for me to checkout correctly ? I was thinking of manually outputing the commit sha with git in the first job. But maybe there is a simpler way or it could be a good idea to output the commit sha in the git-auto-commit action.

```yml
name: Deploy

on:
  workflow_dispatch:
    inputs:
      myvalue:
        description: 'Value to update'
        required: false

jobs:
  update:
    if: ${{ github.event.inputs.myvalue }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Update config
         run: echo ${{ github.event.inputs.myvalue }} > ./config.txt
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update config
      - name: Debug log
        run: git log
  deploy:
    needs: update
    if: ${{ success() || needs.update.result == 'skipped' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Debug log
        run: git log
```

Currently, actions/checkout@v2 uses the workflow ref this way:

```javascript
// https://github.com/actions/checkout/blob/main/src/input-helper.ts

  // Workflow repository?
  const isWorkflowRepository =
    qualifiedRepository.toUpperCase() ===
    `${github.context.repo.owner}/${github.context.repo.repo}`.toUpperCase()

  // Source branch, source version
  result.ref = core.getInput('ref')
  if (!result.ref) {
    if (isWorkflowRepository) {
      result.ref = github.context.ref
      result.commit = github.context.sha

      // Some events have an unqualifed ref. For example when a PR is merged (pull_request closed event),
      // the ref is unqualifed like "main" instead of "refs/heads/main".
      if (result.commit && result.ref && !result.ref.startsWith('refs/')) {
        result.ref = `refs/heads/${result.ref}`
      }
    }
  }
  // SHA?
  else if (result.ref.match(/^[0-9a-fA-F]{40}$/)) {
    result.commit = result.ref
    result.ref = ''
  }
```

**Comment by stefanzweifel** [comment]
If I understood you correctly, the problem is, that in the `deploy`-job `actions/checkout` doesn't correctly checkout your repository, right?


As you're using `workflow_dispatch` I would recommend overriding `ref` to the name of the branch you want to checkout (eg. `master`, `main` or whatever you need).
Being explicit with the branches you want to checkout makes things easier.

[The docs](https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#workflow_dispatch) for `workflow_dispatch` however mention, that the `ref` has to be provided to the payload. So I'm not entirerly sure, what fails here. 🤔 


If this doesn't work for you, you could export a variable in the `update`-job.
Something like this should theoretically work.

```yaml
    - name: Get latest sha
      id: "latest_sha"
      run: >
        LATEST_SHA=$(git rev-parse HEAD);
        echo "::set-output name=latest_sha::${LATEST_SHA}"


  deploy:
    needs: update
    if: ${{ success() || needs.update.result == 'skipped' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ steps.latest_sha.outputs.latest_sha }}
          # Or mabye this syntax, I'm not sure :)
          ref: steps.latest_sha.outputs.latest_sha
```

Does the `deploy`-job without the `ref`-argument checkout the repo? Maybe a simple `git pull` after the `checkout`-step solves the problem too.

**Comment by Aebrathia** [comment]
After experimenting a bit and with your advices I found some satisfying solutions.

> As you're using workflow_dispatch I would recommend overriding ref to the name of the branch you want to checkout (eg. master, main or whatever you need).

I managed to get the branch with `${{ github.ref }}`. `actions.checkout` correctly pulls the latest version of the branch. I found that not specifying `ref:` means using the same commit as the one responsible for the workflow.

The only downside is if there are other commits made between the auto-commit and the checkout they might be used. But it is not a problem in my case.

```yaml
  deploy:
    needs: update
    if: ${{ success() || needs.update.result == 'skipped' }}
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Debug log
        run: git log
```

I also managed to get it working with outputs. However, the syntax for using outputs between jobs is a bit different.

```yaml
jobs:
  job1:
    runs-on: ubuntu-18.04
    outputs:
      output1: ${{ steps.step1.outputs.example }}
    steps:
    - id: step1
      run: echo "::set-output name=example::some-output"
    - run: echo ${{ steps.step1.outputs.example }}

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - run: echo ${{ needs.job1.outputs.output1 }}
```

I didn't try the `git pull`.

Thank you for your time and help ! :)
