### ISSUE TITLE
Automatically approve pull requests

### ISSUE THREAD

**Issue by freearhey** [stefanzweifel/git-auto-commit-action#11]
If the branch requires a review before the merge, the action gives an error:

```sh
! [remote rejected] HEAD -> master (protected branch hook declined)
```

In this regard, is it possible to add to the action automatic approval of pull requests or use with it something like this: [hmarr/auto-approve-action](https://github.com/hmarr/auto-approve-action)?

**Comment by stefanzweifel** [comment]
Can you give me a bit more context, on how you're using this Action? (An example of your workflow would be great; or whihc branch protections are active in your repo).

> In this regard, is it possible to add to the action automatic approval of pull requests or use with it something like this: hmarr/auto-approve-action?

I would like to keep the scope of this Action as small as possible, but it seems the linked Action could totally work with the git-auto-commit-action.
Adding the auto-approve action as a last step would probably work.

**Comment by freearhey** [comment]
This is a very simple workflow, it only runs the script formatting files in the repo after each update. Here is a workflow:

```yml
name: example
on:
  push:
    branches:
      - master
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      
    - name: "git checkout master"
      run: git checkout master
      
    - name: "npm install"
      run: npm install
      
    - name: "npm run format"
      run: npm run format
    
    - name: Commit all changes
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_author_email: example@mail.com
        commit_author_name: Example name
        commit_message: Example message
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

As for adding`hmarr/auto-approve-action` as the last step: this does not work, since an error occurs before on this action. 

And here is the extended version of the error that I see every time:

```sh
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: At least 1 approving review is required by reviewers with write access.        
To https://github.com/example-org/example
 ! [remote rejected] HEAD -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/example-org/example'
##[error]Docker run failed with exit code 1
```

**Comment by stefanzweifel** [comment]
Thanks for the example workflow. 
I will try to recreate your issue over the weekend on an example repository.

Will come back with more information as soon as I have them.

**Comment by stefanzweifel** [comment]
Alright, I could reproduce your problem.

I've created a brand new repository, added a simple app and setup branch protection like this:

<img width="752" alt="Screen-Shot-2019-10-06-12-04-20 09" src="https://user-images.githubusercontent.com/1080923/66267492-8c83cc00-e831-11e9-80fe-065955084980.png">

This is the workflow I've used to format my code:

```yaml
name: Format PHP

on:
  push:
    branches:
      - master

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install
      run: composer install

    - name: Run php-cs-fixer
      run: composer run format

    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I've then created a branch where I change a bit of code and trigger the formatting changes and created a new pull request (workflow is not triggered on the pull request). 
As this is a single private repo with just me in there, I couldn't self-review the code, and had to use my admin privileges to merge the PR.

<img width="756" alt="Screen-Shot-2019-10-06-12-08-11 54" src="https://user-images.githubusercontent.com/1080923/66267548-6ca0d800-e832-11e9-8705-ef44b071caaf.png">

<img width="758" alt="Screen-Shot-2019-10-06-12-08-20 86" src="https://user-images.githubusercontent.com/1080923/66267552-6f9bc880-e832-11e9-949c-68fc41b328fc.png">

The resulting workflow run now fails as expected with the same error message as you got.

<img width="784" alt="Screen-Shot-2019-10-06-12-12-25 38" src="https://user-images.githubusercontent.com/1080923/66267567-9ce87680-e832-11e9-81c8-ed61d7ceb274.png">

---

Now that I've seen how you got this error message, I wonder: Isn't this more of a problem of misconfiguration of protected branches **and** GitHub Actions? 🤔 

Protecting the `master`-branch with "Require pull request reviews before merging", prevents everyone from pushing code directly to the branch. **Every** change has to come through a pull request (even those created by an Action).

As the `git-auto-commit`-Action just uses `git` and not a GitHub API, I don't see a way to "fix" this. It also would feel wrong to me, to add a hack to the Action, which would circumvent the protected-branches feature.

---

Does this explanation help you? Do you think we should mention in the README, that this Action might cause issues if you've activated protected branches in a repository?
