### ISSUE TITLE
error: pathspec '...' did not match any file(s) known to git in Forks

### ISSUE THREAD

**Issue by VaibhavSaini19** [stefanzweifel/git-auto-commit-action#117]
**Version of the Action**
`v4`

**Describe the bug**
The repo uses this action to automatically commit workflow changes back to the repo. But when a PR is made from a branch of a fork (with actions enabled), the actions fails with

```
...
INPUT_BRANCH value: template-issue
From https://github.com/s-katte/React-Code-Pen
 * [new branch]      introduce-collaboration -> origin/introduce-collaboration
 * [new branch]      update-contributing     -> origin/update-contributing
 * [new branch]      update-readme           -> origin/update-readme
error: pathspec 'template-issue' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
I went through [this](https://github.com/stefanzweifel/git-auto-commit-action/issues/6) thread which states that this (or similar) issue was fixed in `v2`, but I am still having this issue

**To Reproduce**
Fork the repo, commit changes in a new branch, create a PR

**Expected behavior**
The changes to be successfully committed in the PR branch which can be merged

I think git is unable to find the branch?

**Screenshots**

Failed workflow: 
https://github.com/s-katte/React-Code-Pen/pull/27/checks?check_run_id=1267689707

**Used Workflow**

```
name: Format
on:
    pull_request_target:
        branches:
            - master
jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: Format
              run: |
                  npm ci
                  npm run format
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply formatting changes
                  branch: ${{ github.head_ref }}
```

**Additional context**
We even tried it without the `branch` option, but it still failed
