### ISSUE TITLE
broken commit action with v4.7.0

### ISSUE THREAD

**Issue by jenschude** [stefanzweifel/git-auto-commit-action#119]
**Version of the Action**
`v4.7.0`

**Describe the bug**

With the latest release (4.7.0) I got this bug:

```
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 

<snip....>

fatal: invalid reference: 
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```

**To Reproduce**

My relevant action configuration

```
      - name: Checkout
        uses: actions/checkout@v2

      - uses: stefanzweifel/git-auto-commit-action@v4.6.0
        with:
          commit_message: "TASK: Updating version in README"
          commit_user_name: Auto Mation
          commit_user_email: automation@...
          commit_author: Auto Mation <automation@...>
```

**Expected behavior**

**Screenshots**

**Used Workflow**

```yaml

# Paste the Workflow you've used here
```

**Additional context**
