### ISSUE TITLE
Invalid status code: 128

### ISSUE THREAD

**Issue by clxmstaab** [stefanzweifel/git-auto-commit-action#121]
since today morning we are running into  errrors:
```
fatal: invalid reference: 
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
```

our workflow looks like (which did not change for a few days now):

```
name: Static analysis

on:
  pull_request:
  repository_dispatch:
    types: [phpstan-baseline-command] # triggered by /phpstan-baseline PR comment

jobs:

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.STAABM_TOKEN }}
        repository: ${{ github.event.client_payload.pull_request.head.repo.full_name }}
        ref: ${{ github.event.client_payload.pull_request.head.ref }}

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        coverage: none
        tools: cs2pr

    - name: Get composer cache directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: ${{ runner.os }}-composer-

    - run: |
        composer config scripts.post-install-cmd --unset # disable post-install-cmd in composer.json
        composer install --prefer-dist --no-progress --no-suggest # install the apps dependencies
        composer bin phpstan install --no-progress

    - run: composer phpstan-baseline # generate baseline
      if: "github.event_name == 'repository_dispatch'"

    - name: Commit changed files
      if: "github.event_name == 'repository_dispatch'"
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply phpstan-baseline changes
        branch: ${{ github.head_ref }}
        file_pattern: '*.neon' # make sure we don't commit our locally changed composer.json

    - run: composer phpstan-pull-request
      if: "github.event_name != 'repository_dispatch'"
```

is this something related to the recent 2 releases from today, which got reverted?

https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v4.7.1
