### ISSUE TITLE
Clarify default author/user/email in readme

### ISSUE THREAD

**Issue by vincerubinetti** [stefanzweifel/git-auto-commit-action#123]
Some suggestions for the readme.

Currently, this is near the top:

```
The default committer is "GitHub Actions actions@github.com", and the default author of the commit is "Your GitHub Username github_username@users.noreply.github.com".
```

Seems kinda weird to put that at the top. I recommend putting that info in the `Usage` section, since that's where all the other defaults are specified. Also I think the explanation of the defaults could be better. 

How about something like this:

```yaml
    # Optional commit user and author settings
    commit_user_name: Jane Smith # defaults to username of commit that triggered the run
    commit_user_email: jane-smith@example.org # defaults to email of commit that triggered the run
    commit_author: Jane Smith <jane-smith@example.org> # defaults to author of commit that triggered the run
```

Also, it seems like that maybe that's not currently how the default author settings work, but I think that's how they [should work](https://github.com/EndBug/add-and-commit), so maybe I'll create a feature request for that.
