### ISSUE TITLE
Using multiple commits

### ISSUE THREAD

**Issue by marcofranssen** [stefanzweifel/git-auto-commit-action#124]
I'm trying to commit multiple commits in my workflow to split the larger amount of changes in smaller commits.

Currently my build is having the following error. 

```bash
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 
Your branch is up to date with 'origin/master'.
INPUT_FILE_PATTERN: modules/moduleA
INPUT_COMMIT_OPTIONS: --no-verify --signoff
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
	modules/moduleB

nothing added to commit but untracked files present
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/ec2-user/actions-runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4.4.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/ec2-user/actions-runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4.4.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

I'm using the following workflow.

```yml
jobs:
  name: Generate code
  steps:      
      - run: .github/generate.sh
    
      - uses: stefanzweifel/git-auto-commit-action@v4.4.0
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Main changes
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true
          file_pattern: README.md main/
          commit_user_name: My Bot
          commit_user_email: mybot@users.noreply.github.com

      - uses: stefanzweifel/git-auto-commit-action@v4.4.0
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Update moduleA
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true
          file_pattern: modules/moduleA
          commit_user_name: My Bot
          commit_user_email: mybot@users.noreply.github.com

      - uses: stefanzweifel/git-auto-commit-action@v4.4.0
        if: github.ref == 'refs/heads/master'
        with:
          commit_message: Update moduleB
          commit_options: '--no-verify --signoff'
          skip_dirty_check: true
          file_pattern: modules/moduleB
          commit_user_name: My Bot
          commit_user_email: mybot@users.noreply.github.com
```

As not every module does always have changes, sometimes there is no need to make that commit. Currently the workflow fails because moduleB has changes and moduleA doesn't while trying to commit moduleA.

Am I doing something wrong? Or could this be a feature which would only try to commit if the pattern staged files.
