### ISSUE TITLE
Error: Invalid status code: 1

### ISSUE THREAD

**Issue by simioluwatomi** [stefanzweifel/git-auto-commit-action#125]
**Version of the Action**
`v4.7.2`

**Describe the bug**
When there are no ch

**To Reproduce**
I use the action below to run Php CS Fixer in a repo. The action works when there are file changes by Php CS Fixer but fails with the error code in the title and screenshot.

**Expected behavior**
I expect that the action should skip making a commit when there are no changes to commit and not fail the whole workflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/22191563/97651421-40b74c80-1a5c-11eb-8ed6-46fa11813964.png)

**Used Workflow**

```yaml
name: Php CS Fixer

on: [push]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}

            - name: Run php-cs-fixer
              uses: docker://oskarstark/php-cs-fixer-ga
              with:
                args: --config=.php_cs

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: Apply php-cs-fixer changes
```
