### ISSUE TITLE
Unexpected input(s) 'commit_message', 'branch', valid inputs are ['entryPoint', 'args']

### ISSUE THREAD

**Issue by introwit** [stefanzweifel/git-auto-commit-action#127]
YAML:

```yaml
name: Format PHP using PHP-CS-FIXER

on:
  push:
    branches:    
      - develop
    paths:
    - '**.php'

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.composer/cache/files
        key: dependencies-composer-${{ hashFiles('composer.json') }}

    - name: Install dependencies
      run: composer install

    - name: Run php-cs-fixer
      run: ./vendor/bin/php-cs-fixer fix

    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Warning in the actions UI:
<img width="797" alt="Screenshot 2020-11-20 at 12 17 27 AM" src="https://user-images.githubusercontent.com/11228182/99711661-117a8500-2ac8-11eb-93a4-be38e256c728.png">
