### ISSUE TITLE
artifact in autocommit

### ISSUE THREAD

**Issue by KonstantinKlepikov** [stefanzweifel/git-auto-commit-action#134]
We can upload an artifacts (for example as https://github.com/actions/upload-artifact). How commit that artifacts to branch?

**Comment by stefanzweifel** [comment]
Artifacts uploaded with the linked Action are uploaded to GitHub's servers and not to the repository. (By default they also expire after 90 days; [see docs](https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts))

If you want to push artifacts to the repository, you would have to copy the generated artifacts into your GitHub repository in the Github Actions Workflow (eg. `cp /path/to/generated/artifact.txt /repo_path/my_artifact.txt`). 

git-auto-commit will then detect a change in your repository, create a commit with your artifact and push it to the remote repository.

**Comment by KonstantinKlepikov** [comment]
hmm ... he sees artifacts. It's all good :)

as example

```
  - uses: stefanzweifel/git-auto-commit-action@v4
    with:
      commit_message: Autoupdate
      branch: main
      file_pattern: someartifact.art
```
