### ISSUE TITLE
fatal: invalid refspec 'HEAD:'

### ISSUE THREAD

**Issue by reypm** [stefanzweifel/git-auto-commit-action#148]
I am running into https://github.com/stefanzweifel/git-auto-commit-action/issues/8 and I am not sure why since I am leaving the value as defaulted which should be the current branch. What I could be missing here?

```yaml
name: Code Style

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP CS Fixer
        uses: docker://oskarstark/php-cs-fixer-ga
        with:
          args: --config=.php_cs.dist

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: Fix styling
        env:
          GITHUB_TOKEN: ${{ secrets. GITHUB_TOKEN }}
```
