### ISSUE TITLE
Action sometimes fails when jobs are re-run

### ISSUE THREAD

**Issue by jojo2357** [stefanzweifel/git-auto-commit-action#155]
**Version of the Action**
`v4.10.0` `v4.9.2`

**The bug**
When using this action in a workflow, it fails when the workflow makes changes to the repo during a re-run of the job.

**To Reproduce**
1. Create a workflow that makes changes and runs on push
2. Make a commit to activate the workflow and ensure the workflow applies changes
3. Change the source of an action in the workflow to ensure that the workflow will create new changes and the repo will be dirty
4. Request re-run jobs (since you havent made a new commit, to apply the new action, you must re-run jobs)
5. This job will fail

**Expected behavior**
The action will complete without error and create a new commit

**Used Workflow**

```yaml
name: create stats

on: push

jobs:
  generate-file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Code_Stats
        uses: jojo2357/CodeStats@Dev
        with:
          root_dir: 'src/main/java/frc'

      - name: Git Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4.10.0
        with:
          branch: ${{ github.head_ref }}
          commit_message: Woooooooooo stats
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
```

**Additional context**
A log of a failed run can be found [here](https://github.com/FRCTeam5199/Robot-Code-2021/runs/2358682512?check_suite_focus=true)
