### ISSUE TITLE
Cannot `--amend --no-edit`

### ISSUE THREAD

**Issue by OJFord** [stefanzweifel/git-auto-commit-action#159]
I'm rendering markdown in an Action on a cron, and want it to just amend the last commit rather than create a continuous stream of 'render' commits that don't have any value.

Unfortunately though (I've tested this), this prevents `--amend --no-edit` from working:

https://github.com/stefanzweifel/git-auto-commit-action/blob/5dd17c3b53a58c1cb5eaab903826abe94765ccd6/entrypoint.sh#L86-L88

since the `--no-edit` is effectively ignored if a `--message` is specified.

I'm not sure what to suggest as a fix, but two options I can think of are:

1. Check if `--no-edit` appears in `commit_options`; do not specify `-m ..` if it does;
2. Add an explicit `with: amend: true` config, which adds `--amend --no-edit` to options and doesn't specify `-m ..`

**Comment by stefanzweifel** [comment]
Thanks for reporting.
Seems you have found an edge-case for git-auto-commit. The [`--amend`](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend) docs mention that `-m` `-F` or `-c` has to be missing in order to reuse the previous message. 🤔 

Am I understanding this right that you only set the `commit_options` in your workflow? Like this?

```
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_options: '--amend --no-edit'
```

Or do you also use the `--force` push option?
(Just wondering how this could even work if you're just ammending something to a commit which has already been pushed to a remote repository)

---

Checking for certain values in `commit_options` feels a bit dirty. I would rather like to keep things simple.
To you think it would work, if you extract the previous commit message and supply it to the Action? (See code below)

```yaml
- name: Get last commit message
  id: last-commit-message
  run: |
    echo "::set-output name=msg::$(git log -1 --pretty=%B | cat)"

- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: ${{ steps.last-commit-message.outputs.msg }}
    commit_options: '--amend --no-edit'
```

Or does `--ammend --no-edit` not work at all with `--message`?

**Comment by OJFord** [comment]
> Am I understanding this right that you only set the commit_options in your workflow? Like this?

Yes, at least that's what I tried.

> Or do you also use the --force push option?

... 🤦🏻 I should, thanks, just hadn't had it work yet so hadn't realised my omission.

> To you think it would work, if you extract the previous commit message and supply it to the Action? (See code below)

That's exactly what I've done (I don't think the `cat`'s necessary?) to work around it, yep. Just a bit messy/annoying - it also needs (at least, when `runs-on: ubuntu-latest` it does) an additional step to install git.

**Comment by stefanzweifel** [comment]
I can understand the frustration.

However, I've kept the Action low level by design. 
Adding if-clauses that detect if `--ammend` is in the argument list and then changing the executed code doesn't sit well with me right now. Hope you understand.

>  it also needs (at least, when runs-on: ubuntu-latest it does) an additional step to install git.

This seems weird. According to the [virtual-environments](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md) repo, `ubuntu-latest` (Ubuntu 20.04) ships with `git`. (Would also be surprising to me if it didn't. We're talking about **Git**Hub after all ☺️)

---

I tried to test the approach with providing the commit_message as I mentioned above, but the global Actions outage today blocks me from actually running this.

If this works as expected I'more than happy to add it as an example to the README.

**Comment by stefanzweifel** [comment]
Actions is working again and I did a little test in a test-repo.

The approach of defining the message in combination with `--amend --no-edit` and `--force` seems to work.

```yaml
    - name: Get last commit message
      id: last-commit-message
      run: |
        echo "::set-output name=msg::$(git log -1 --pretty=%B)"

    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit
      with:
        commit_message: ${{ steps.last-commit-message.outputs.msg }}
        commit_options: '--amend --no-edit'
        push_options: '--force'
```

But using the Action in that way vaporized my previous git history - as is expected when using `--amend` in combination with already published commits.
https://github.com/stefanzweifel/git-auto-commit-action-demo-app/commits/master

> You should understand the implications of rewriting history if you amend a commit that has already been published. (See the "RECOVERING FROM UPSTREAM REBASE" section in git-rebase[1].)
> https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---amend

So I wouldn't recommend doing that. Just let the Action generate a new commit. 
Or I would encourage to write your own git-commit and push logic to solve the problem in your project.
