### ISSUE TITLE
Occasional 403 Forbidden / 128 Internal Error Code

### ISSUE THREAD

**Issue by gerryfletch** [stefanzweifel/git-auto-commit-action#164]
**Version of the Action**
`v4.11.0`

**Describe the bug**
Occasionally the action will fail with an internal status code of `128`, reporting `403` Forbidden:
```
remote: Permission to {org}/{repo}.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/{org}/{repo}/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.11.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/Users/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.11.0/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

(Omitted the repo and org)

This happens when git does not exit cleanly, but since it works 50% of the time I'm not sure that it's to do with my configuration.

**To Reproduce**
This behaviour is flaky. I would say roughly 50% of my builds fail with this. All are created in the same way (they're dependabot updates). Rerunning the build usually fixes it, but this is costing me significant minutes in GHA.

**Expected behavior**
100% success rate.

**Used Workflow**
```yaml
name: Update Cocoapods Dependencies

on:
  push:
    branches:
      - dependabot/npm_and_yarn/**
  pull_request:
    branches:
      - dependabot/npm_and_yarn/**

jobs:
  run:
    name: Run pod install
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: c-hive/gha-yarn-cache@v1

      - run: yarn install --non-interactive --frozen-lockfile --network-timeout 100000

      - name: Cache pods
        uses: actions/cache@v1
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Cocoapods Packages
        run: pushd ios && pod install --verbose && popd

      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Bump Cocoapods Packages
          branch: ${{ github.head_ref }}
```
