### ISSUE TITLE
action not running when using alpine:latest container on job

### ISSUE THREAD

**Issue by zanven42** [stefanzweifel/git-auto-commit-action#166]
**Version of the Action**
`v4`

**Describe the bug**

**To Reproduce**
use an alpine base container for the job with this task.

**Expected behavior**
expect the action to run and commit / tag commits.

**Screenshots**
https://github.com/zanven42/workflow-debugger/actions/runs/1019597903

**Used Workflow**

```yaml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    container: alpine:latest
    steps:
      - name: Obtain Latest Git ONLY within container for checkout
        run: apk add git docker --update-cache

      - name: Checkout Repo Action
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Buildx docker image build and push images
        id: build
        run: |
          echo "testing" >> README.md
          
      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[CICD] commit"
```

**Additional context**
below is the logs output when starting the action. If it is known what packages are needed for this action a minimal alpine image could be setup for this action to use so that it can run in isolation cleanly and avoid this issue.

```Started: bash /__w/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
Error: spawn bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn bash',
  path: 'bash',
  spawnargs: [
    '/__w/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh'
  ]
}
Error: spawn bash ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)```
