### ISSUE TITLE
Commit if there are file by pattern in the commit itself

### ISSUE THREAD

**Issue by Mte90** [stefanzweifel/git-auto-commit-action#175]
**Is your feature request related to a problem? Please describe.**
It is not clear by the action if can do that check, in our case we need to check the commit as we need to generate some pdf and reupload it.
The issue is that it there will a timestamp so the files will be different also if they aren't after all and we don't want to commit with this files.

Our idea was to check if the commit include files of a pattern/folder included in this way the action can be execute to push the changes.

**Comment by stefanzweifel** [comment]
The `file_pattern` is used in the "is dirty"-check and determines if files should be added and committed ([see code](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L44)); so I think what you want to do should work.

I think examples make everything easier. 
If I understood you correctly, your workflow looks something like this:

```yaml
# other code related to when workflow is triggered

-   run: /execute/some/code

-   uses: stefanzweifel/git-auto-commit-action@v4
    id: auto-commit-action
    with:
        file_pattern: src/*.js

-   name: "Generate PDFs if previously a commit has been created"
    if: steps.auto-commit-action.outputs.changes_detected == 'true'
    run: /generate/pdfs

-   name: "Commit generated PDFs"
    if: steps.auto-commit-action.outputs.changes_detected == 'true'
    uses: stefanzweifel/git-auto-commit-action@v4
    with:
        file_pattern: src/*.pdf
        commit_message: "Add auto generated PDFs"
```

If not, could you please share more information of what you want to achieve here?
