### ISSUE TITLE
error when nothing to commit

### ISSUE THREAD

**Issue by GmBodhi** [stefanzweifel/git-auto-commit-action#177]
**Version of the Action**
`v4`

**Describe the bug**
Whenever local is up to date with origin the process fails and resulting in this error:

**To Reproduce**
Try to commit without making any changes.

**Expected behavior**
The process shouldn't fail and resulting in a workflow failure unless we specify to ignore the error

**Screenshots**
![image](https://user-images.githubusercontent.com/71921036/134754069-2caa1296-9bac-408d-a14d-6390a0e8942d.png)

**Used Workflow**

![image](https://user-images.githubusercontent.com/71921036/134754123-28a641fd-313d-4133-82fa-2d01b5bba77c.png)

**Comment by stefanzweifel** [comment]
Thanks for reporting!

Currently can't figure out what the problem here is. `skip_dirt_check` is covered by [a test ](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/tests/git-auto-commit.bats#L148-L162) and your workflow basically uses all the default values except the commit message. 🤔 

Will have a closer look over the days.

**Comment by stefanzweifel** [comment]
@GmBodhi Unfortunately I can't reproduce your issue. 

In https://github.com/stefanzweifel/git-auto-commit-action/commit/f6048aa2acaebea86483c05cd872213addabc819 I've added a test that covers your exact use case (I think?). Hover, the test passes without throwing errors.

Could you share more about your use case? Pasting your workflow here would probably help.
What is happening before `git-auto-commit`-action is used?

**Comment by GmBodhi** [comment]
Actually, I have hundreds of files. Probably 300 I guess.

**Comment by GmBodhi** [comment]
```yml
name: Example

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"

jobs:
  Example:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node v14
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: yarn install

      - name: Run Config
        run: yarn run config

      - name: Generate examples
        run: |
          cd example-processor
          node index.js
      - name: Generate Config
        run: |
          cd example-processor
          node generateConfig.js
      - name: Format Code
        run: |
          npm i prettier -g
          git pull -a
          prettier --write .
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "automated: Examples generated (actions)"
          file_pattern: "."
          skip_dirty_check: false
          skip_fetch: false
```
That `git pull -a` was added for extra safety, but either way the result was same
