### ISSUE TITLE
Document minimum set of permissions required by this action

### ISSUE THREAD

**Issue by ericcornelissen** [stefanzweifel/git-auto-commit-action#179]
If `permissions: read-all` (or something similar, [ref](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#permissions)) is set at the top-level of a workflow this action won't work. It would be helpful if the documentation included a description of the minimum set of permissions required by this action. From my testing, it seems the minimum required permission is `content: write` ([ref](https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idpermissions)). So, a full example would be:

```yaml
name: php-cs-fixer

on:
  pull_request:
  push:
    branches:
      - "main"

permissions: read-all

jobs:
  example:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply php-cs-fixer changes
```

I can draft a paragraph on this topic and add it with a Pull Request, but I'm not sure where in the README it should go.
