### ISSUE TITLE
Can't find node in PATH, trying to find a node binary on your system

### ISSUE THREAD

**Issue by EmilienLeroy** [stefanzweifel/git-auto-commit-action#18]
**Version of the Action**
`v2.3.0`

**Describe the bug**
I use [husky](https://github.com/typicode/husky) to run lint before commit. An error appear when the action is call, i think is due to the pre commit.

**To Reproduce**
This my configuration :
```yml
name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
      
    - name: build
      run: npm run build
      
    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: 📦 Build dist
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```

And i run this during the pre commit :
```json
  "lint-staged": {
    "{src,test}/**/*.ts": [
      "prettier --write",
      "git add"
    ]
  },
```

**Expected behavior**
Run the pre commit before commit without error.

**Screenshots**
https://github.com/Kamiapp-fr/kami-collection/runs/322604011
![image](https://user-images.githubusercontent.com/31723722/69705605-3119e000-10f6-11ea-9b24-cc96a7d4d630.png)

**Comment by stefanzweifel** [comment]
Hi Emilien,

Thanks for the detailed issue!
The problem occours, as the Action run on the `alpine/git:1.0.7` docker image where node is not available. ([Source](https://github.com/stefanzweifel/git-auto-commit-action/blob/master/Dockerfile#L1))

I first have to test, if and how we could switch to a Docker image that supports both `git` and `node`. As `husky` is quite a popular pre-commit solution I think it would make sense to support it in the Action.

In the meantime you should be able to disable the hooks by passing `--no-verify` to the Action (if that is something that would work in your workflow)

```diff
    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: 📦 Build dist
        branch: master
+       commit_options: '--no-verify'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by EmilienLeroy** [comment]
Thanks for your answers,

I have made a test without husky and it work perferctly : https://github.com/Kamiapp-fr/kami-collection/commit/2fc3c2a5775a3ab70e3528f4309f1c72c8ad2181/checks?check_suite_id=331010381
![image](https://user-images.githubusercontent.com/31723722/69708529-0f235c00-10fc-11ea-8d0c-3aab8e9551df.png)

**Comment by stefanzweifel** [comment]
Great!
I will see what I can do to add support for husky. Will keep you updated through this issue.

**Comment by zhangyoufu** [comment]
Please consider rewrite this action using Typescript, so that CLI tools in the host environment can be used.

**Comment by stefanzweifel** [comment]
A rewrite in JS/TS has been on my mind lately. (Would like to have a test suite to make sure everything works as expected).

Thanks for the link. Will checkout if we can do something similar in this Action.

**Comment by stefanzweifel** [comment]
I've made some first attempts of an easy rewrite in JS as mentioned by @zhangyoufu here: https://github.com/stefanzweifel/git-auto-commit-action/blob/86f0c11c06a83f9b92c87e0111b1b8f9037a77bd/index.js

However, using the updated Action in a demo results in a broken Workflow (See log [here](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/runs/439488539#step:5:13))

---

My bandwith is quite limited right know and I think the Action works for 80% of the usecases. I've written more thought on a JavaScript rewrite in #44.
If someone in this thread has the time and energy to start working for it, go for it. PRs are most welcomed.

I might revisit the idea of a JS rewrite in 2-3 months.

**Comment by zhangyoufu** [comment]
> However, using the updated Action in a demo results in a broken Workflow (See log [here](https://github.com/stefanzweifel/git-auto-commit-action-demo-app/runs/439488539#step:5:13))

You're invoking `sh` instead of `bash` in `index.js`.

https://github.com/stefanzweifel/git-auto-commit-action/blob/86f0c11c06a83f9b92c87e0111b1b8f9037a77bd/index.js#L18-L20

I think change `[[ ... ]]` to `[ ... ]` in `entrypoint.sh` will make this script POSIX shell-compliant.

https://github.com/stefanzweifel/git-auto-commit-action/blob/86f0c11c06a83f9b92c87e0111b1b8f9037a77bd/entrypoint.sh#L30-L32

**Comment by stefanzweifel** [comment]
@zhangyoufu Thanks. Will give it a try later this week.

**Comment by stefanzweifel** [comment]
Thanks @zhangyoufu for the help. Your suggestion solved the issues.
I've prepared a PR, which changes the Action to use `node12` instead of `Docker`. See #45.

I would appreciated it if any of you would test the changes in your projects before I merge and release a new major version.

Update your workflow files to use the PR branch like this.

```diff
- - uses: stefanzweifel/git-auto-commit-action@v3.0.0
+ - uses: stefanzweifel/git-auto-commit-action@refactor/switch-to-js
```

Please leave your feedback in the PR #45.

**Comment by EmilienLeroy** [comment]
I have tried with the js version. Husky work well but i get an error for the commit.
https://github.com/Kamiapp-fr/kami-collection/runs/464095052
![image](https://user-images.githubusercontent.com/31723722/75135495-f702af00-56e1-11ea-9000-bba00b4b5ace.png)

My config file: 
https://github.com/Kamiapp-fr/kami-collection/blob/test/pre-commit/.github/workflows/build.yml

```yml
name: Build

on:
  push:
    branches:
    - master
    - test/pre-commit

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install
      run: npm install
      
    - name: build
      run: npm run build
      
    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@refactor/switch-to-js
      with:
        commit_message: 📦 Build dist
        branch: test/pre-commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
```
