### ISSUE TITLE
Unexpected input(s) 'token'

### ISSUE THREAD

**Issue by ndahlquist** [stefanzweifel/git-auto-commit-action#181]
**Version of the Action**
`v4.x.x`

**Describe the bug**
I am trying to add the `token` param, as described at https://github.com/stefanzweifel/git-auto-commit-action#commits-made-by-this-action-do-not-trigger-new-workflow-runs.

Unfortunately, it appears the `token` param is no longer supported:

```
Warning: Unexpected input(s) 'token', valid inputs are ['commit_message', 'branch', 'commit_options', 'add_options', 'status_options', 'file_pattern', 'repository', 'commit_user_name', 'commit_user_email', 'commit_author', 'tagging_message', 'push_options', 'skip_dirty_check', 'skip_fetch', 'disable_globbing']
```

**To Reproduce**
1. Add `token` param.
2. Run job.

**Expected behavior**
Action should accept token param, or documentation updated to remove this feature.

**Used Workflow**

```yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply lint fixes
          token: ${{ secrets.SWARM_BOT_GITHUB_PAT }}
```

**Additional context**
If this was intentionally removed, happy to submit a PR to remove this from the readme.

Is there a different workaround for triggering new runs from pushed commits? Thank you!
