### ISSUE TITLE
Checks never finish if you add a commit to a PR

### ISSUE THREAD

**Issue by CodeCasterNL** [stefanzweifel/git-auto-commit-action#185]
**Version of the Action**
`v4.1.2`

**Describe the bug**
When php-cs-fixer fixes some code and commits it through this git-auto-commit-action, then the pull request's checks will never finish.

**To Reproduce**
0. Create a branch
1. Commit then push some code that php-cs-fixer would love to correct
2. Create a PR for that branch into another
3. The checks run for the initial commit
4. The check creates an additional commit
5. The checks never run on this additional commit

**Expected behavior**
The checks should re-run or something? 

**Screenshots**
Pull Request:
![PR checks](https://user-images.githubusercontent.com/1726333/141119301-590769ee-9a9b-43a5-9447-cfc9669f8d2c.png)

Pending check on fixed commit:
![PR checks (waiting)](https://user-images.githubusercontent.com/1726333/141119476-6a48ee7a-cbf2-4cf6-afd0-643ea05c66a7.png)

Succesful checks on initial commit:
![PR checks successful](https://user-images.githubusercontent.com/1726333/141119684-732c3835-2b86-41e8-bffa-e525a81c0e73.png)

**Used Workflow**

```yaml
name: Fix Code Style and Build

on:
  pull_request:

jobs:
  php-cs-fixer:
    name: PHP Coding Standards Fixer on ${{ matrix.operating-system }})
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ ubuntu-latest ]
        php-versions: [ '7.4' ]

    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: php-cs-fixer

      - name: Run php-cs-fixer
        run: php-cs-fixer fix -v

      - name: Commit php-cs-fixer changes, if any
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: fix: Apply php-cs-fixer changes
          branch: ${{ github.head_ref }}

  symfony:
    name: Symfony (PHP ${{ matrix.php-versions }} on ${{ matrix.operating-system }})
    needs: php-cs-fixer
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4']

    runs-on: ${{ matrix.operating-system }}

    services:
      # ...
    steps:

      - name: Git Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # do the build...
```
