### ISSUE TITLE
Fatal error when auto-commit

### ISSUE THREAD

**Issue by eXorus** [stefanzweifel/git-auto-commit-action#2]
Hello,

I tried to use your action but it doesn't work, I have a fatal error at the end.

```
Run stefanzweifel/git-auto-commit-action@v1.0.0
  env:
    GITHUB_TOKEN: ***
    COMMIT_MESSAGE: hello
    COMMIT_AUTHOR_NAME: CS Fixer
    COMMIT_AUTHOR_EMAIL: john.doe@example.com
/usr/bin/docker run --name b3e3f72439fc3af08948f989a19a825463598a_d79f18 --label b3e3f7 --workdir /github/workspace --rm -e GITHUB_TOKEN -e COMMIT_MESSAGE -e COMMIT_AUTHOR_NAME -e COMMIT_AUTHOR_EMAIL -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/php-mime-mail-parser/php-mime-mail-parser":"/github/workspace" b3e3f7:2439fc3af08948f989a19a825463598a
HEAD detached at 8866c5a
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

	new file:   build/logs/clover.xml
	new file:   test.log

[detached HEAD 84cac5b] hello
 Author: CS Fixer <john.doe@example.com>
 2 files changed, 515 insertions(+)
 create mode 100644 build/logs/clover.xml
 create mode 100644 test.log
fatal: could not read Username for 'https://github.com': No such device or address
##[error]Docker run failed with exit code 128
```

FYI my step action:
```
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: "hello"
        COMMIT_AUTHOR_NAME: "CS Fixer"
        COMMIT_AUTHOR_EMAIL: "john.doe@example.com"
```

**Comment by isaced** [comment]
same problem [here](https://github.com/isaced/crystal-web-framework-stars/commit/c01594ab61d4d64277881ae75e5f07d6dbea9754/checks).

**Comment by stefanzweifel** [comment]
Hi folks 👋

Sorry for the late response. Somehow I wasn't watching this repo and didn't get a notification for this issue.

I just got access to the new beta and can reproduce your error. Don't understand yet, why this happens … so any helps is greatly appreciated!

**Comment by stefanzweifel** [comment]
The syntax for actions changed with the new beta too.
So I've pushed some changes to the [`dev`](https://github.com/stefanzweifel/git-auto-commit-action/tree/dev)-branch but still couldn't resolve the issue.

The error is definitely caused by the `git push -u origin HEAD` command. It seems the way the repo is checked out through [actions/checkout](https://github.com/actions/checkout/) breaks this actions.

----

To use the cutting edge version of this action, you would have to update your workflow with the following step:

```yaml
- uses: stefanzweifel/git-auto-commit-action@dev
  with:
    commit_author_email: john.doe@example.com
    commit_author_name: John Doe
    commit_message: Apply automatic changes
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by stefanzweifel** [comment]
Further investigation shows, this comes from the fact that `actions/checkout` checkouts a repository in a detached state.
Also the `GITHUB_TOKEN` seems to have more restricted permissions.

Issue with more information: https://github.com/actions/checkout/issues/6

**Comment by eXorus** [comment]
Hello @stefanzweifel and @isaced ,

I did a test without your action and it works with several issues:
https://github.com/php-mime-mail-parser/php-mime-mail-parser/pull/254/files

- The first issue `could not read Username for 'https://github.com': No such device or address` is related to authorization I did a `git remote set-url origin https://eXorus:${{ secrets. GITHUB_TOKEN }}@github.com/php-mime-mail-parser/php-mime-mail-parser` and it works
- The second issue is that the commit to fix will not trigger the others actions like unit tests because Github has event restriction https://help.github.com/en/articles/events-that-trigger-workflows (An action in a workflow run can't trigger a new workflow run)
- For the second issue you can add a custom secret and put a personal token inside to replace the GITHUB_TOKEN
- The last issue is related to the fork (and I'm here) it doesn't work if someone push a PR.... maybe we should have 2 strategy one for a fork and one for our PR.

**Comment by stefanzweifel** [comment]
I could fix my test repo in a similar way.

Added a step to checkout a specific git-ref, so the repo is no longer detached:

```yaml
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
```

And then added a step to set the origin URL. I've used a custom PAT (Personal Access Token).

```yaml
    - name: Set Git Origin URL
      run: git remote set-url origin https://$TOKEN:x-oauth-basic@github.com/stefanzweifel/laravel-github-actions-demo
      env:
        TOKEN: ${{ secrets.TOKEN }}
```

I have to test, if it still works with the `GITHUB_TOKEN`.
In this setup, the Commit from the action triggers the workflow again.

Maybe the git-auto-commit action should ask for a `TOKEN` env/secret? The README could then describe, what the difference between a PAT and a GITHUB_TOKEN does to the workflow? 🤔

**Comment by eXorus** [comment]
Yes but how do you manage the PR from someone else ? I'm not sure the token will be set. The secret is only accessible by the main repo not the fork repo.

And for me php-cs-fixer is very usefull when someone else push a PR on my repo.

**Comment by stefanzweifel** [comment]
Ah sorry, misunderstood the problem.
Yeah, that doesn't sound like a good idea.

Running php-cs-fixer in all PRs is also something I want to implement for my OSS projects.

**Comment by tiagobrito** [comment]
I think now GIthub allow this, now they show this warning:

```
You are in 'detached HEAD' state. You can look around, make experimental
 changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -
```

**Comment by stefanzweifel** [comment]
Saw the updated output too.

`git switch -c $GITHUB_REF` caused an infinite loop for me, as `$GITHUB_REF` looks like `/ref/heads/name-of-branch`. 
I've used `${GITHUB_REF:11}` now to get `name-of-branch`.

My php-cs-fixer action now looks like this.

```yaml
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Checkout branch
      run: git switch "${GITHUB_REF:11}"

    - name: Run php-cs-fixer
      uses: docker://oskarstark/php-cs-fixer-ga

    - name: Set git remote URL
      run: git remote set-url origin https://$TOKEN:x-oauth-basic@github.com/stefanzweifel/laravel-github-actions-2
      env:
        TOKEN: ${{ secrets.TOKEN }}

    - name: Commit changed files
      uses: stefanzweifel/git-auto-commit-action@dev
      with:
        commit_author_email: foo@bar.com
        commit_author_name: Stefan Zweifel
        commit_message: Apply php-cs-fixer changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

However, as @eXorus mentioned, this setup currently requires a PAT and doesn't seem to work with `$GITHUB_TOKEN`. 😞

**Comment by stefanzweifel** [comment]
v2.0.0 of this Action has been released which fixes this issue.
https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v2.0.0

I've recently stumbled upon [this action](https://github.com/elstudio/actions-js-build/blob/41d604d6e73d632e22eac40df8cc69b5added04b/commit/entrypoint.sh) by another developer. 
Instead of setting the remote url through `git remote set-url`, the Action authenticates itself with GitHub through the `.netrc`-file.

I've tested this in my test-projects, and everything seems to work as indented. As the Action still uses the `GITHUB_TOKEN`-secret, no new workflow is triggered by the pushed commit.

Please checkout the updated [README](https://github.com/stefanzweifel/git-auto-commit-action/tree/v2.0.0) on how to use Action in your workflows.

@eXorus concerning triggering and pushing to a forked repo: I read in a forum thread or in an issue, that the Actions of a fork are actually run on the fork and not on the main repository. 
Otherwise the fork could read secrets from the main repository through actions.

Does this latest version work for your setup?

---

I'm closing this issue now, as the main error ("fatal: could not read Username for 'https://github.com': No such device or address") has been fixed.

**Comment by tiagobrito** [comment]
I tried this last version and it's working 🎉
Many thanks!

**Comment by eXorus** [comment]
Thanks for you work.
I don't have any usage if it doesn't work for a fork because on my side I always push PSR compliant but I woulk like to be sure that PR that I received from others devs are also PSR compliant.

**Comment by stefanzweifel** [comment]
@eXorus Maybe this will work after Actions is out of beta and all users have access to it 🤔 

Definitely something I'm interested too for my OS-projects.

**Comment by localheinz** [comment]
@stefanzweifel 

Not sure if this is related, but @OskarStark and I have been testing the action with a dedicated GitHub token created for a bot user that has write privileges, but we currently see the action fail with the following output:

```
  Run stefanzweifel/git-auto-commit-action@v4.1.1
  with:
    branch: master
    commit_author: example-bot <example-bot@example.com>
    commit_message: Enhancement: Update example-file.txt
    commit_user_email: example-bot@example.com
    commit_user_name: example-bot
    file_pattern: backend\/example-file.txt
    repository: .
  env:
    EXAMPLE_BOT_EMAIL: example-bot@example.com
    EXAMPLE_BOT_NAME: example-bot
    GITHUB_TOKEN: ***

Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/entrypoint.sh
INPUT_REPOSITORY value: .
"::set-output name=changes_detected::true"
INPUT_BRANCH value: master
Switched to a new branch 'master'
M	backend/example-file.txt
Branch 'master' set up to track remote branch 'master' from 'origin'.
INPUT_FILE_PATTERN: backend\/example-file.txt
INPUT_COMMIT_OPTIONS:
[master 6a3e009c] Enhancement: Update example-file.txt
 1 file changed, 1 insertion(+), 1 deletion(-)
INPUT_TAGGING_MESSAGE:
 No tagging message supplied. No tag will be added.
fatal: could not read Username for 'https://github.com': No such device or address
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

The corresponding step definition looks like this:

```yaml
            - name: "Commit example-file.txt"
              uses: stefanzweifel/git-auto-commit-action@v4.1.1
              with:
                  branch: master
                  commit_author: "${{ env.EXAMPLE_BOT_NAME }} <${{ env.EXAMPLE_BOT_EMAIL }}>"
                  commit_message: "Enhancement: Update example-file.txt"
                  commit_user_email: "${{ env.EXAMPLE_BOT_EMAIL }}"
                  commit_user_name: "${{ env.EXAMPLE_BOT_NAME }}"
                  file_pattern: backend\/\example-file.txt
              env:
                  GITHUB_TOKEN: "${{ secrets.EXAMPLE_BOT_TOKEN }}"
```

Do you have an idea what the problem could be?

**Comment by stefanzweifel** [comment]
@localheinz Since v3.0.0 the Action no longer requires a token in the Action itself. You would have to pass the token to the `actions/checkout@v2` step, like this:

```
- uses: actions/checkout@v2
  with:
    token: ${{ secrets.EXAMPLE_BOT_TOKEN }}
```

This Action no longer does any authentication with GitHub itself. We just use whatever the `actions/checkout`-Action does.

**Comment by localheinz** [comment]
Thank you, @stefanzweifel - giving this a try!

**Comment by retorquere** [comment]
I'm not sure whether to post here or open a new one, but I'm getting this error in one of my repos -- but not another:

```

Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: 
fatal: could not read Username for 'https://github.com': No such device or address
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

with this config

```
    - uses: stefanzweifel/git-auto-commit-action@v4
      name: update ipynb from py
      with:
        commit_message: Convert percent-py notebooks
        file_pattern: ./*.ipynb
        skip_dirty_check: false
```
