### ISSUE TITLE
Add tagging only on a specific branch

### ISSUE THREAD

**Issue by nosisky** [stefanzweifel/git-auto-commit-action#207]
I would like to skip tagging for a specific branch, I don't know If there is an existing implementation for that. At the moment I have:

```
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message:  commit message
            tagging_message:  module version
            commit_user_name: Developer
            commit_user_email: developer@dev.com
```
            
   I would want something like:
   ```
          - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message:  commit message
            if branch === master
            tagging_message:  module version
            commit_user_name: Developer
            commit_user_email: developer@dev.com
    ```
