### ISSUE TITLE
fatal: Not a git repository 

### ISSUE THREAD

**Issue by eeliu** [stefanzweifel/git-auto-commit-action#222]
**Version of the Action**
`v4.x.x`

**Describe the bug**

Commit nothing !

**Screenshots**

![image](https://user-images.githubusercontent.com/27064129/169939626-9bb95676-71ef-4df0-9d08-535c649987db.png)

**Used Workflow**

```yaml
    runs-on: ubuntu-latest
    container: ghcr.io/pinpoint-apm/pinpoint-c-agent/golang-build-env-1.16:latest
    needs: go16
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: update go mod under libs
        run: |
          cd libs
          for dir in * ; do cd  $dir; go get github.com/pinpoint-apm/go-aop-agent@${{ github.sha }}; cd ..; done
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update libs module to the latest commit
```

Action : https://github.com/pinpoint-apm/go-aop-agent/runs/6566178919?check_suite_focus=true
