### ISSUE TITLE
Push options don't apply when pushing tags, and there are no tag pushing options

### ISSUE THREAD

**Issue by justinmchase** [stefanzweifel/git-auto-commit-action#236]
**Version of the Action**
`v4.x.x`

**Describe the bug**
I'm trying to overwrite a tag. My code change is to update code in the repo based on the version tag just created, but I want the tag to apply to the new commit so I need to be able to force push the tag, however the push options seem to not apply when pushing tags and there doesn't appear to be a separate field for tag push options.

My workflow step:
```yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ github.event.release.tag_name }}"
          tagging_message: "${{ github.event.release.tag_name }}"
          branch: master
          push_options: '--force'
```

Error message thats produced despite the `--force` push option.
```
INPUT_TAGGING_MESSAGE: 1.1.2
fatal: tag '1.1.2' already exists
Error: Invalid status code: 128
```

**To Reproduce**
1. Build a workflow that runs on release publish (see below) and has tagging_message
2. Create a release

**Expected behavior**
I expect the tag to be force pushed

**Screenshots**
N/A

**Used Workflow**

```yaml
name: Publish

on:
  release:
    types: [published]

jobs:
  version:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@master
      - uses: justinmchase/version@master
        with:
          action: set
          value: ${{ github.event.release.tag_name }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "${{ github.event.release.tag_name }}"
          tagging_message: "${{ github.event.release.tag_name }}"
          branch: master
          push_options: '--force'
```

**Additional context**
