### ISSUE TITLE
Standard use stops workflow after committing  (Waiting for status to be reported)

### ISSUE THREAD

**Issue by altherlex** [stefanzweifel/git-auto-commit-action#244]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

After committing, the other jobs get a `Expected — Waiting for status to be reported` and the workflow gets stuck

### Steps to reproduce

standard use re-triggers workflow

### Example Workflow

```yaml
name: CI

on:
  pull_request:
    branches: [ main ]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  ...
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event.pull_request.draft == false
    
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Bump version
        run: |
          echo 'my_tag' > VERSION

      - name: Update VERSION file
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: 'VERSION'
          commit_message: 'Update VERSION'
```
```


### Relevant log output

_No response_
