### ISSUE TITLE
Unable to commit into PRs from forks

### ISSUE THREAD

**Issue by staabm** [stefanzweifel/git-auto-commit-action#25]
We configured a php-cs-fixer like the example in the readme suggest, using a Personal Access Token so it should work in forks.

It does not work though, see the build error in  https://github.com/redaxo/redaxo/pull/3092/checks?check_run_id=373678935

Is there anything obvious wrong?
Is this not a supported feature?

The workflow is configured in https://github.com/redaxo/redaxo/blob/master/.github/workflows/csfix.yml

**Comment by stefanzweifel** [comment]
Hi,

Thanks for the detailed issues with links to actual logs :)
Hmm, it seems the action is trying to push the changes to a branch on the original repository instead of the forked one.

Have to do some digging on how we could support running the action in forks.

**Comment by stefanzweifel** [comment]
Ok, here's what I could figure out:

- GitHub Actions and PRs from forks (still) do not play well together. This was a design decision by GitHub. In short, their concern is that a fork could update the workflow and read secrets.
  - Some examples of others: [github.community](https://github.community/t5/GitHub-Actions/Actions-not-working-correctly-for-forks/td-p/35545), https://github.com/cclauss/autoblack/issues/8, https://github.community/t5/GitHub-Actions/Can-t-push-to-forked-repository-on-the-original-repository-s/m-p/35916/highlight/true#M2372

A user mentioned that running actions on forked PRs is easier with a GitHub app or with slash commands (see https://github.com/peter-evans/slash-command-dispatch).

- Running the action with checkout@v2 doesn't help either. The workflow checkouts the main target repo, and not the forked repo (I think). Here's my test PR: https://github.com/stefanzweifel/git-auto-commit-action-demo-app/pull/6

Looks like as long as GitHub does not change how Actions work, this seems not possible. I will make a note in the README.

**Comment by localheinz** [comment]
@staabm 

As an alternative, `friendsofphp/php-cs-fixer` could be run on the `master` branch after merge:

```yml
name: "Clean-up"

on:
  push:
    branches:
      - "master"

  coding-standards:
    name: "Coding Standards"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2.0.0"

      - name: "Install locked dependencies with composer"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Run friendsofphp/php-cs-fixer"
        run: "vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --verbose"

      - name: "Commit modified files"
        uses: "stefanzweifel/git-auto-commit-action@v2.5.0"
        with:
          branch: "master"
          commit_message: "Fix: Run friendsofphp/php-cs-fixer"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```
