### ISSUE TITLE
GITHUB_OUTPUT: unbound variable

### ISSUE THREAD

**Issue by SlinToWin** [stefanzweifel/git-auto-commit-action#254]
### git-auto-commit Version

v4.15.2

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

Hello, we have a regression bug with the latest patch version v4.15.2
The outcome is an error on the autocommit step preventing the commit.

We use the autocommit action in an enterprise GH installation.

### Steps to reproduce

Just using the 4.15.2 in a GH Enterprise environment

### Example Workflow

```yaml
---
name: Scale up DEV cluster

on:
  workflow_dispatch:
  schedule:
    - cron: 15 6 * * 1-5
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SecretToken }}
      - name: Scale up environments
        run: |
          set -e
          sh bin/cluster-scale-up.sh
      - name: Commit scale up
        uses: stefanzweifel/git-auto-commit-action@v4.15.1
        with:
          commit_message: "deploy: cluster scale up"
```

### Relevant log output

```shell
Started: bash /runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: .
/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh: line 14: GITHUB_OUTPUT: unbound variable
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/runner/_work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
