### ISSUE TITLE
Doesn't fail when missing git

### ISSUE THREAD

**Issue by MatthijsBurgh** [stefanzweifel/git-auto-commit-action#260]
### git-auto-commit Version

V4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

I am using the `container` option of GH actions. My container doesn't have git installed. So your script tries to call git, but it doesn't exist.

I would expect your action would fail in that case. But it doesn't.  It just exits with success.

### Steps to reproduce

Use the container option of a job in GH actions in combination with a container without git installed.

### Tried solutions

Temporary workaround is just to install git manually.

### Example Workflow

```yaml
jobs:
  job_id:
    name: JOB_NAME
    runs-on: ubuntu-latest
    container:
      image: CONTAINER_WITHOUT_GIT
    steps:
      - uses: stefanzweifel/git-auto-commit-action@v4
        ...
```

### Relevant log output

```shell
Run stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: Update Build
    file_pattern: build/*.js
    repository: .
    commit_user_name: github-actions[bot]
    commit_user_email: github-actions[bot]@users.noreply.github.com
    commit_author: MatthijsBurgh <MatthijsBurgh@users.noreply.github.com>
    skip_dirty_check: false
    skip_fetch: false
    skip_checkout: false
    disable_globbing: false
    create_branch: false
  env:
    ROS_DISTRO: noetic
/usr/bin/docker exec  26ef51d71514a8ec76f32381a7b5a5eb419c2349484f3a2d057c99c41dd5e798 sh -c "cat /etc/*release | grep ^ID"
Started: bash /__w/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: build/*.js
/__w/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh: line 59: git: command not found
Working tree clean. Nothing to commit.
```
