### ISSUE TITLE
Make branch optional

### ISSUE THREAD

**Issue by yelizariev** [stefanzweifel/git-auto-commit-action#27]
**Is your feature request related to a problem? Please describe.**

I mainly use the action to compile code (e.g. rst to html). Which happens in PR branches on pushing, not in pull request. Currently, I either need to hardcode branch (e.g. master), or add an extra step like following:
```
    - run: |
        BRANCH="${GITHUB_REF:11}"
        echo "::set-env name=BRANCH::$BRANCH"
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v2.4.0
      with:
        branch: ${{ env.BRANCH }}
```

**Describe the solution you'd like**

When not set, the branch should be computed. It could be something like this;

```
BRANCH=${INPUT_BRANCH}
if [[ -z "$INPUT_BRANCH ]]
then
    BRANCH=${GITHUB_REF:11}
fi

```
