### ISSUE TITLE
Does not trigger other actions listening to pull request update

### ISSUE THREAD

**Issue by kjy5** [stefanzweifel/git-auto-commit-action#274]
### git-auto-commit Version

v4.16.0

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

Does not trigger pull request synchronize when making commits back to a branch in a pull request.

Example situation:
- A pull request triggers several distinct GitHub Action workflows to run, including one that includes a call to `git-auto-commit`
- All workflows run as expected
- **The workflow with `git-auto-commit` successfully makes a commit and pushes the changes back to the branch. This _should_ trigger other workflows to run again, but they don't.** 
  - All other workflows do run if I make a new commit to the branch that the pull request is occurring on

### Steps to reproduce

Have two workflows with triggers
```yml
on:
  pull_request:
    types: [opened, synchronize, reopened]
```

One of these can do whatever, the other will do something that changes the files and later has
```yml
- uses: stefanzweifel/git-auto-commit-action@v4
```
To commit the changes (this works).

The expected behavior is that this commit back to the branch will trigger a rerun of both of these workflows since they trigger on pull request "synchronize".

### Tried solutions

- Tried different trigger methods
- Tried adding `edited` as in `types` (does not work)

### Example Workflow

```yaml
name: Reformat and Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch:

concurrency:
  group: "reformat-and-lint"
  cancel-in-progress: true

jobs:
  reformat-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@v3

      - name: 📦 Setup Node.js and caching
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: "npm"

      - name: 🔨 Install
        run: npm i

      - name: 🧹 Reformat
        run: npx prettier --write .

      - name: 🚨 Lint
        run: npx eslint .

      - name: ⬆️ Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Reformat and Lint
```
