### ISSUE TITLE
Invalid reference, error 128

### ISSUE THREAD

**Issue by lukepighetti** [stefanzweifel/git-auto-commit-action#278]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

A contributor has a fork branch called `contributor:card` and is trying to merge it in to `lukepighetti:main`

It appears that `git-auto-commit` is trying to commit to `lukepighetti:card` instead of `contributor:card`

```yaml
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: task gen
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update generated files
          file_pattern: "*.g.dart"
```

When new generated files are found and this action is triggered to commit the new files, I get the following error

```
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
[20](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:21)
INPUT_REPOSITORY value: .
[21](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:22)
INPUT_STATUS_OPTIONS: 
[22](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:23)
INPUT_FILE_PATTERN: *.g.dart
[23](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:24)
INPUT_BRANCH value: card
[24](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:25)
From https://github.com/lukepighetti/mastodon_dart
[25](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:26)
 * [new branch]      lukepighetti/actions-task-2 -> origin/lukepighetti/actions-task-2
[26](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:27)
 * [new branch]      lukepighetti/cleanup-nov-15 -> origin/lukepighetti/cleanup-nov-15
[27](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:28)
 * [new branch]      lukepighetti/null-safety -> origin/lukepighetti/null-safety
[28](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:29)
 * [new branch]      main       -> origin/main
[29](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:30)
fatal: invalid reference: card
[30](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:31)
Error: Invalid status code: 128
[31](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:32)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
[32](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:33)
    at ChildProcess.emit (node:events:390:28)
[33](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:34)
    at maybeClose (node:internal/child_process:1064:16)
[34](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:35)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5) {
[35](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:36)
  code: 128
[36](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:37)
}
[37](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:38)
Error: Invalid status code: 128
[38](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:39)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
[39](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:40)
    at ChildProcess.emit (node:events:390:28)
[40](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:41)
    at maybeClose (node:internal/child_process:1064:16)
[41](https://github.com/lukepighetti/mastodon_dart/actions/runs/3846888265/jobs/6552794001#step:6:42)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
```
