### ISSUE TITLE
 fatal: unable to access 'https://github.com/username/myrepo/': The requested URL returned error: 403

### ISSUE THREAD

**Issue by papanito** [stefanzweifel/git-auto-commit-action#284]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

[My workflow ](https://github.com/papanito/github-actions-workflows/blob/main/.github/workflows/publish-workflows.yaml) fails to push changes.

```
remote: Permission to papanito/ansible-role-cloudflared.git denied to username.
fatal: unable to access 'https://github.com/username/myrepo/': The requested URL returned error: 403
```

### Steps to reproduce

1. Create a PAT
2. Store the pat as `GH_TOKEN`
3. Manual run workflow using the workflow below

I have a secret called `GH_TOKEN`. In your docu you reference the token as `GITHUB_TOKEN` which I cannot define, as it's [not allowed](https://docs.github.com/en/actions/security-guides/encrypted-secrets)

> Names must not start with the GITHUB_ prefix.

### Example Workflow

```yaml
4 lines (53 sloc) 1.61 KB
name: Workflow Publisher
on:
  push:
    branches: ['develop', 'main']
    paths:
      - 'ansible-roles/**'
  workflow_dispatch:

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [
          'ansible-role-cloudflared',
          'ansible-role-crowdsec',
          'ansible-role-diskmounter',
          'ansible-role-systemd_notifiers',
          'ansible-role-ttrss',
          'ansible-role-backup',
          'ansible-role-git'
        ]
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v3
        with:
          path: main
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.GH_TOKEN}}
          ref: main
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/ansible-roles/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ci:update workflows
          commit_user_email: papanito@wyssmann.com
          commit_user_name: GitHub Actions
          repository: ./${{ matrix.target_repo }}
        continue-on-error: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
```

### Relevant log output

```shell
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: ./ansible-role-cloudflared
INPUT_STATUS_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_BRANCH value: 
M	.github/workflows/build.yml
M	.github/workflows/release.yml
Your branch is up to date with 'origin/main'.
INPUT_ADD_OPTIONS: 
INPUT_FILE_PATTERN: .
INPUT_COMMIT_OPTIONS: 
INPUT_COMMIT_USER_NAME: GitHub Actions
INPUT_COMMIT_USER_EMAIL: papanito@wyssmann.com
INPUT_COMMIT_MESSAGE: ci:update workflows
INPUT_COMMIT_AUTHOR: papanito <papanito@users.noreply.github.com>
[main 71d29e1] ci:update workflows
 Author: papanito <papanito@users.noreply.github.com>
 2 files changed, 19 insertions(+), 19 deletions(-)
INPUT_TAGGING_MESSAGE: 
No tagging message supplied. No tag will be added.
INPUT_PUSH_OPTIONS: 
remote: Permission to papanito/ansible-role-cloudflared.git denied to papanito.
fatal: unable to access 'https://github.com/papanito/ansible-role-cloudflared/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

**Comment by stefanzweifel** [comment]
Thanks for reporting.

So your workflow first checks out the `papanito/github-actions-workflows` repository and then immediately clones of the repos in the matrix. A bash scripts is run and the changes should be commited back to the matrix repo.

Good call to use a PAT here, as the normal `GITHUB_TOKEN` wouldn't have the necessary permissions to push to another repository anyway. (The `GITHUB_TOKEN` in the README always represents the [default token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) GitHub provides.)

I'm not really sure, why this error happens. As you use `actions/checkout` to clone the matrix-repos and pass your PAT to the step, the repository should have been setup with the correct permissions. (git-auto-commit fully relies on the authentication-setup done by `actions/checkout`).

Maybe you could give it a go with the following workflow?
(I've removed the permissions block, the initial `actions/checkout` of `papanito/github-actions-workflows` and removed the `env`-block in the git-auto-commit step).

```yaml
name: Workflow Publisher
on:
  push:
    branches: ['develop', 'main']
    paths:
      - 'ansible-roles/**'
  workflow_dispatch:

jobs:
  publish-workflow-template:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_repo: [
          'ansible-role-cloudflared',
          'ansible-role-crowdsec',
          'ansible-role-diskmounter',
          'ansible-role-systemd_notifiers',
          'ansible-role-ttrss',
          'ansible-role-backup',
          'ansible-role-git'
        ]
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          path: ${{ matrix.target_repo }}
          token: ${{ secrets.GH_TOKEN}}
          ref: main
      - name: Update workflows
        shell: bash
        run: |
          mkdir -p .github/workflows/
          cp ../main/ansible-roles/* .github/workflows/
        working-directory: ./${{ matrix.target_repo }}
      - name: Publish workflows
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ci:update workflows
          commit_user_email: papanito@wyssmann.com
          commit_user_name: GitHub Actions
          repository: ./${{ matrix.target_repo }}
        continue-on-error: false
```

In the README of your repository I saw, you use this setup, as shared workflows are only available to orgs and not personal accounts.

I think "reusable workflows" are available for personal accounts too: https://docs.github.com/en/actions/using-workflows/reusing-workflows

This allows you to extract the core logic of a workflow to a central place and reference that workflow in other workflows in single repositories.

Here's an example from an org. In a central repository is a workflow to update a changelog file.

- https://github.com/laravel/.github/blob/main/.github/workflows/update-changelog.yml

The consumers then just setup the respective triggers and "include" the workflow.

- https://github.com/laravel/laravel/blob/10.x/.github/workflows/update-changelog.yml
- https://github.com/laravel/horizon/blob/5.x/.github/workflows/update-changelog.yml

But that doesn't solve the issues of triggering a workflow and updating multiple repositories at one.
