### ISSUE TITLE
`commit_user_name` has no effect

### ISSUE THREAD

**Issue by adamlui** [stefanzweifel/git-auto-commit-action#287]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

Specifying a custom username in `commit_user_name` has no effect, instead `github-actions[bot]` is always the committer

### Steps to reproduce

In workflow, set `commit_user_name` to a value that is not `github-actions[bot]`

### Tried solutions

- tried using `auto-sync[bot]` as `commit_user_name` value
- tried using `'auto-sync[bot]'` as `commit_user_name` value

### Example Workflow

```yaml
name: Sync chatgpt/bravegpt to kudoai/bravegpt/greasemonkey

on:
  push:
    branches:
      - master
    paths:
      - 'chatgpt/bravegpt/**'
    if: 'github.actor != "auto-sync[bot]"'

jobs:
  sync-bravegpt:
    runs-on: ubuntu-latest
    steps:

      # Checkout adamlui/userscripts
      - name: Checkout adamlui/userscripts
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: adamlui/userscripts
          path: adamlui/userscripts

      # Checkout kudoai/bravegpt
      - name: Checkout kudoai/bravegpt
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.REPO_SYNC_PAT }}
          repository: kudoai/bravegpt
          path: kudoai/bravegpt

      # Sync adamlui/userscripts/chatgpt/bravegpt to kudoai/bravegpt/greasemonkey
      - name: Sync bravegpt
        run: rsync -av --delete ${{ github.workspace }}/adamlui/userscripts/chatgpt/bravegpt/ ${{ github.workspace }}/kudoai/bravegpt/greasemonkey/
      
      # Push to kudoai/bravegpt
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          push_options: '--force'
          add_options: '--all'
          commit_user_name: auto-sync[bot]
          commit_message: '${{ github.event.head_commit.message }} (synced from adamlui/userscripts)'
          file_pattern: 'greasemonkey/*'
          repository: kudoai/bravegpt
```

### Relevant log output

Activity log shows `github-actions[bot]` as the constant committer despite above YML

![image](https://user-images.githubusercontent.com/10906554/227877421-2b2f14e8-a499-4492-99f0-bf324c2035f9.png)
