### ISSUE TITLE
--amend option removes all git history

### ISSUE THREAD

**Issue by jawoznia** [stefanzweifel/git-auto-commit-action#294]
### git-auto-commit Version

v4

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

I try to create a workflow that will update PRs on change. I don't want to create a new commit and would prefer to `amend` the automatic change to head commit in PR.

What I found is that for some reason the whole history is replaced with single new commit.

### Steps to reproduce

It should be enough to run the `example workflow`.

### Tried solutions

It is fine if I remove the `amend` command but it is not desired solution.

### Example Workflow

```yaml
my config 


name: Release plz 

on:
  pull_request:

jobs:
  print_commit_name:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    if: startsWith(github.head_ref, 'release_')
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
    - name: Create new file 
      run: echo '\n// New commit' > src/main.rs 
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_options: '--amend'
        push_options: '--force'
```
