### ISSUE TITLE
move GITHUB_TOKEN to inputs

### ISSUE THREAD

**Issue by yelizariev** [stefanzweifel/git-auto-commit-action#30]
Pros:

* we can set ``required: true`` and other properties in ``action.yml`` and handle the argument on action level and not just in scripts
* we can check whether token is custom or built-in

It's implemented here https://github.com/stefanzweifel/git-auto-commit-action/pull/26/files, but that PR has other updates

**Comment by stefanzweifel** [comment]
@yelizariev I've created a PR for this in #35.

I've also tested this in my demo app here:
https://github.com/stefanzweifel/git-auto-commit-action-demo-app/runs/387688173

However, I'm not really convinced why this is the better or what the upsides are.
Currently it would still be possible to override the GitHub token with a personal access token (PAT) like this:

```yaml
    - uses: stefanzweifel/git-auto-commit-action@master
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: my-random-token
```

Other projects I've seen so far all use `env.GITHUB_TOKEN`.

Could you elaborate the following point with some examples? 
> and handle the argument on action level and not just in scripts


---

Or why *this* action should make checks on the token?
> we can check whether token is custom or built-in

**Comment by yelizariev** [comment]
> we can check whether token is custom or built-in

Potential use is for choosing default values for Author and Commiter
https://github.com/stefanzweifel/git-auto-commit-action/issues/29

> and handle the argument on action level and not just in scripts

Currently, there is no check that github token is provided. It seems, though, that the GITHUB_TOKEN is always available in the environment. While on using the input, it's explicitly specified that argument is required. 

I think I tried something like in your example
```
    - uses: stefanzweifel/git-auto-commit-action@master
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: my-random-token
```
But somehow it doesn't. Not sure, though. It could be just some  author\commiter behaviour. 

 > Other projects I've seen so far all use env.GITHUB_TOKEN.

I actually got this idea from other github actions: 
* https://github.com/github-actions-x/commit/commit/b48217b3e6c03c7785d764f063c8915b116f0416
* maybe another one too. I cannot fine now

**Comment by stefanzweifel** [comment]
> But somehow it doesn't. Not sure, though. It could be just some author\commiter behaviour.

Ah I see. I think the structure in my example might be from the old beta. The official docs now also use a similar example like you mentioned: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/authenticating-with-the-github_token#using-the-github_token-in-a-workflow

```yaml
name: Pull request labeler
on:
- pull_request
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

---

With the release of [actions/checkout@v2](https://github.com/actions/checkout) we could also eliminate the whole token thing completely. v2 stores the credentials by default in the local git directory and allows subsequent Actions to push back to the repository.
I've prepared this in #36 (still have to update the README)

Would this change break your workflows? 
I think even in scenarios where you checkout multiple repositories in 1 workflow you still can leverage the power of `checkout@v2` and will be able to push to both cloned repositories.
