### ISSUE TITLE
No step output is being generated

### ISSUE THREAD

**Issue by ChristianVermeulen** [stefanzweifel/git-auto-commit-action#323]
### git-auto-commit Version

V5

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

When trying to use the output in order to place a comment on the PR, the next step is never triggered because there is no output.

### Steps to reproduce

- Run the autocommit and make sure it has something to commit
- Run a next step with `if: steps.auto-commit-action.outputs.changes_detected == 'true'`

The next step will not run.

### Example Workflow

```yaml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autofixed your phpscs for ya
          commit_user_name: christianvermeulen
          commit_user_email: christian.vermeulen@******.be
          commit_author: christianvermeulen <christian.vermeulen@******.be>

      - name: Notify PR owner
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hey @${{ github.event.pull_request.head.repo.owner.login }}, I've taken the liberty to fix your CS (${{steps.auto-commit-action.outputs.commit_hash}}). Don't forget to pull before you push new commit!
```

### Relevant log output
I added a debug step to echo all steps output like so:

```yml
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Autofixed your phpscs for ya
          commit_user_name: christianvermeulen
          commit_user_email: christian.vermeulen@******.be
          commit_author: christianvermeulen <christian.vermeulen@******.be>

      - name: debug
        run: |
          echo "${{ toJson(steps) }}"

      - name: Notify PR owner
        if: steps.auto-commit-action.outputs.changes_detected == 'true'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hey @${{ github.event.pull_request.head.repo.owner.login }}, I've taken the liberty to fix your CS (${{steps.auto-commit-action.outputs.commit_hash}}). Don't forget to pull before you push new commit!
```

The output of that json is as follows:
```json
{
    "composer-cache": {
      "outputs": {
        "{DIR}": "{/home/runner/.cache/composer/files}"
      },
      "outcome": "success",
      "conclusion": "success"
    }
  }
```

As you can see, there is no output from the auto-commit job, only from a different composer-cache job.
