### ISSUE TITLE
repo in detached `HEAD` state wasnt causing problems before

### ISSUE THREAD

**Issue by gosuto-inzasheru** [stefanzweifel/git-auto-commit-action#378]
### git-auto-commit Version

v6

### Machine Type

Ubuntu (eg. ubuntu-latest)

### Bug description

we have this action running in two separate repos ([1](https://github.com/BalancerMaxis/bal_tools/pull/105))([2](https://github.com/BalancerMaxis/multisig-ops/pull/2113)), and in both v6 now gets stuck on:
>Error: Repository is in detached HEAD state. Please make sure you check out a branch. Adjust the  input accordingly.

i understand this is a feature not a bug (introduced in #357), but we never had problems before with the old version. what are we doing wrong?

### Steps to reproduce

eg https://github.com/BalancerMaxis/bal_tools/actions/runs/15573050946/job/43863386559?pr=105 or https://github.com/BalancerMaxis/multisig-ops/actions/runs/15573089744/job/43852869376?pr=2113

### Example Workflow

```yaml
name: Lint

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Black
        uses: psf/black@stable
        with:
          options: "--verbose"
          version: "24.10.0"

      - name: Auto commit
        uses: stefanzweifel/git-auto-commit-action@v6.0.0
        with:
          commit_message: "style: ci lint with `black`"
```

### Relevant log output

```shell

```

**Comment by leettaylor** [comment]
Having the same problem too. I think this is the [relevant bit in the readme](https://github.com/stefanzweifel/git-auto-commit-action#:~:text=Note%20that%20we%20explicitly%20specify%20%24%7B%7B%20github.head_ref%20%7D%7D%20in%20the%20checkout%20Action.%20This%20is%20required%20in%20order%20to%20work%20with%20the%20pull_request%20event%20(or%20any%20other%20non%2Dpush%20event).) for fixing it.

I think it needs `github.head_ref` in the `checkout` action.

```
steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}
```
