### ISSUE TITLE
3.0 does not trigger new github action builds

### ISSUE THREAD

**Issue by staabm** [stefanzweifel/git-auto-commit-action#43]
I had a setup inspired by the 3.0 release notes to fix the cs automatically with php-cs-fixer.

the commits are triggered but no builds are started.

after reverting back to 2.5 with https://github.com/staabm/annotate-pull-request-from-checkstyle/pull/25 it works again

**Comment by stefanzweifel** [comment]
Thanks for reporting!
So you're using the default `GITHUB_TOKEN` in v2.5.0? And if a commit is made by the Action, it triggers a new Actions Workflow run?

According to GitHub, this shouldn't be possible. 🤔 

Or are you using a Personal Access Token? If yes, I think you should be able to use v3 of this action and update the token in `actions/checkout@v2` according to [their docs](https://github.com/actions/checkout#usage).

Will do further investigation though.

**Comment by staabm** [comment]
> So you're using the default `GITHUB_TOKEN` in v2.5.0? And if a commit is made by the Action, it triggers a new Actions Workflow run?

nope, I am using a personal access token. with the default token it does not work

**Comment by stefanzweifel** [comment]
Hi again and sorry for the late reply.

As mentioned in the [v3.0.0 release](https://github.com/stefanzweifel/git-auto-commit-action/releases/tag/v3.0.0), this Action no longer accepts a token. The `GITHUB_TOKEN` or your personal access token has to be passed to the `actions/checkout` action.

I'v copied and updated the Workflow file from your mentioned PR below. (See the new `token` input near `actions/checkout`).

```yaml
name: Format PHP

on: pull_request

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        token: ${{ secrets.STAABM_TOKEN }}

    - name: "Install dependencies with composer"
      run: "composer install --no-interaction --no-progress --no-suggest"

    - name: "Run friendsofphp/php-cs-fixer"
      run: "vendor/bin/php-cs-fixer fix --config=.php_cs --diff --diff-format=udiff --verbose"

    - uses: stefanzweifel/git-auto-commit-action@v3.0.0
      with:
        commit_message: Apply php-cs-fixer changes
        branch: ${{ github.head_ref }}
```

(I saw you've closed your upstream issue in your repo, so I don't know how relevant this still is).

---

In addition I've just updated the README with a better troubleshoot section. I've also added a short text around the problem described in this issue and how to solve it.

https://github.com/stefanzweifel/git-auto-commit-action#commit-of-this-action-does-not-trigger-a-new-workflow-run
