### ISSUE TITLE
branch not found on pull_request

### ISSUE THREAD

**Issue by ApplebaumIan** [stefanzweifel/git-auto-commit-action#55]
**Version of the Action**
`v4.1.1`

**Describe the bug**
I have an action to change a config file on pull_request because my master branch is protected. I need the file of the branch being pulled into master committed to the current branch. 
```yml
name: Setup Jazzy Config
on: [pull_request]
jobs:
   add_permalink:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PATH
          sed '$d' .jazzy.yaml > temp
          cat temp > .jazzy.yaml
          rm temp
          echo "github_file_prefix: https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/tree/${{ github.sha }}" >> .jazzy.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Apply jazzy config changes
          branch: ${{ github.head_ref }}
          commit_user_name: ApplebaumIan
          commit_user_email: ian.tyler@electricbluefish.com
          commit_author: Ian Applebaum <ian.tyler@electricbluefish.com>
          commit_options: ''
          token: ${{ secrets.KEY_TOKEN }}
```
I get this error 
```error
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/entrypoint.sh
INPUT_REPOSITORY value: .
"::set-output name=changes_detected::true"
INPUT_BRANCH value: finishJazzySetup
error: pathspec 'finishJazzySetup' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.1/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
**To Reproduce**
1. have a protected master branch
2. write an action that uses `on: [pull_request]`
3. `branch: ${{ github.head_ref }}`
4. make a pull request and git-auto-commit-action will say that git doesn't recognize the branch.

**Expected behavior**
git should recognize the current branch of the pull request.
