### ISSUE TITLE
Error when run this action on pull_request event

### ISSUE THREAD

**Issue by tripheo0412** [stefanzweifel/git-auto-commit-action#66]
**Version of the Action**
`v4.1.15`

**Describe the bug**
When workflow use this action was triggered with pull_request

**To Reproduce**
1. Add `on: [pull_request]` to workflow.yml
2. Commit anything
3. See error

**Expected behavior**
This action will fail due to how actions/checkout@v2 handle pull_request event with default `ref` parameter

**Screenshots**

![image](https://user-images.githubusercontent.com/25382052/80152106-49c6ed00-85e5-11ea-876d-0b03d54bc005.png)

**Additional context**
When I have a look at actions/checkout@v2 log or run git branch to debug, seems like it reinitialized .git folder and only has this branch: `refs/remotes/pull/1/merge` (see image below)
Which leads to, when your action checking out `${{ github.head_ref }}` it will report error.
![image](https://user-images.githubusercontent.com/25382052/80152625-3c5e3280-85e6-11ea-9bf4-3a4c6292b240.png)

**Potential fix**
Provide `ref: ${{ github.head_ref }}` to force actions/checkout@v2, checkout the "right way"
```
on: [pull_request]

jobs:
  test-my-action:
    runs-on: ubuntu-latest
    name: Testing auto log committer action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
```
