### ISSUE TITLE
"tags push" event fails because repo has a detached head

### ISSUE THREAD

**Issue by joemaller** [stefanzweifel/git-auto-commit-action#70]
**Version of the Action**
`v4.1.6`

**Describe the bug**
Trying to push from a tag action fails. Repository has a detached head.  Originally reported in https://github.com/stefanzweifel/git-auto-commit-action/issues/69#issuecomment-621411447

Action trigger is:

```yaml
  push:
    tags: ["v*"]
```
git-auto-commit-action fails because the repository is not on a branch.

**To Reproduce**

1. Example workflow below, or fork [joemaller/push-from-tag-event](https://www.github.com/joemaller/push-from-tag-event)
2. Run `npm version patch && git push --follow-tags`

**Expected behavior**
Modified README file is committed and updated in the repository. 

**Additional context**
The error message in GitHub Actions is:
```
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use

    git push origin HEAD:<name-of-remote-branch>

Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.6/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4.1.6/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Sample workflow**
```yaml

name: Push from Tag

on:
  push:
    tags: ["v*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Modify Readme
        run: echo $(date) >> README.md

      - name: Commit README
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Update README
          file_pattern: README.md
```
