### ISSUE TITLE
Fatal Error around head ref

### ISSUE THREAD

**Issue by RMSD** [stefanzweifel/git-auto-commit-action#8]
Hey, I'm trying to use this action to build my website on master. I'm seeing changes, but the action isn't setting head right:

```
[detached HEAD bf27a08] Apply automatic changes
fatal: invalid refspec 'HEAD:'
```
Here's my action run: https://github.com/RMSD/EdgeSheet/runs/241481009. It's definitely picking up some changes.

Copied straight from the github action marketplace page in my yml:

```
- name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply automatic changes
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/RMSD/EdgeSheet/blob/master/.github/workflows/deployment.yml

Am I just misreading the docs, or is this a legit error? It seems like `github.head_ref` is supposed to be a legit env variable from GH.

**Comment by stefanzweifel** [comment]
Hi,

It seems the `github.head_ref` value is empty. `head_ref` is unfortunately only available in the context of a Pull Request (eg: `on: pull_request` instead of `on: push`).

As youre workflow in your project is only triggered when something is pushed to `master`, you could just hard code the value:

```yaml
name: Automatic deployment

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10
      uses: actions/setup-node@v1
      with:
        node-version: 10
    - name: npm install, build, and deploy
      run: |
        npm install
        npm run build --if-present
        npm run deploy
    - name: Auto Commit changed files
      uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Apply automatic changes
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

An earlier version of this action could determine the correct push branch on it's own. Recent changes to Actions made this very complicated (See https://github.com/actions/checkout/issues/6). That's why the `branch`-argument exists now.
