### ISSUE TITLE
Can't find branch: pathspec 'branch' did not match any file know to git

### ISSUE THREAD

**Issue by Benwick91** [stefanzweifel/git-auto-commit-action#81]
**Version of the Action**
`v4`

**Describe the bug**
Because we have a protected develop and master branch, we want to push changelog files to a specific 'changelog' branch. But it seems that the action can't find the branch.

The error message:

```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: changelog
error: pathspec 'changelog' did not match any file(s) known to git
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 1
}
Error: Invalid status code: 1
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Expected behavior**
The action pushes and updates the changelog file on the changelog branch.

**Used Workflow**

```yaml
name: Changelog

on:
  push:
    branches:
      - develop

jobs:
  write-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Update Changelog
        run: echo -en "changes" >$changelog_filepath
        env:
          changelog_filepath: ${{ github.workspace }}/CHANGELOG.md
      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update changelog
          branch: changelog
```

Thank you!

**Comment by stefanzweifel** [comment]
I guess the problem might be, that the `changelog`-branch does not exist in the checked out repo on GitHub Actions.

This action tries to switch to the provided branch name. See code here: https://github.com/stefanzweifel/git-auto-commit-action/blob/master/entrypoint.sh#L39-L44

In orde for this to work for you, you would have to update your checkout step like this:

```diff
 - name: Checkout Repository
   uses: actions/checkout@v2
+  with:
+     ref: 'checkout'
```

The commit action should then work as expected.

**Comment by Benwick91** [comment]
Thank you for the fast answer. 
You mean:
```
 - name: Checkout Repository
   uses: actions/checkout@v2
   with:
     ref: changelog
```

and not `ref: 'checkout'` or am I wrong? :)
