### ISSUE TITLE
Using --amend as commit_options doesn't work when working directory is clean 

### ISSUE THREAD

**Issue by goetzc** [stefanzweifel/git-auto-commit-action#82]
Hello, thanks for this Action. I'm experiencing some kind of unexpected behavior when using the `--amend` Git option, which I'm describing below.

**Version of the Action**
`v4.3.0`

**Describe the bug**
When using the `--amend` Git commit option on the `commit_options` field, the Action doesn't work if the working directory is clean, showing the message ["Working tree clean. Nothing to commit."](https://github.com/stefanzweifel/git-auto-commit-action/blob/v4.3.0/entrypoint.sh#L25).

**To Reproduce**
- Use the `--amend` option on the `commit_options` field.
- When the working directory is empty, nothing is changed.

**Expected behavior**
The commit should be amended and pushed.

**Used Workflow**

```yaml
   … # Some previews manual Git changes …

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: Bump version to ${{ steps.git-version.outputs.tag }}
        commit_options: --amend  # <-- This is 
        tagging_message: ${{ steps.git-version.outputs.tag }}
```

**Additional context**
My purpose is to perform some Git operations generating a new commit, and finally using this action and the `--amend` option to modify the commit and push it.
