### ISSUE TITLE
Question: Signing off commits

### ISSUE THREAD

**Issue by TGTGamer** [stefanzweifel/git-auto-commit-action#85]
Heya guys,

Possibly a stupid question, but I'm doing circles at the moment. 

I want to have my workflow signoff the commit, but can't figure out how to do it and the documentation isn't amazing for this xD

You can see the pull request I made to test this here: https://github.com/TGTGamer/.github/pull/22
Here's my workflow: 

```yml
name: Documentation

on:
  push:
    branches:
      - master
      - docs/auto-update
    paths:
      - "docs/**"
      - "README.md"
      - "CHANGELOG.md"

jobs:

  # Automatically copies and renames README, SUMMARY & CHANGELOG to be correct for both github Wiki and Gitbook
  copyfiles:
    name: Copy & Rename docs files
    runs-on: ubuntu-latest
    if: github.event_name != 'gollum'
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy Files
        run: |
          cp README.md docs/README.md
          cp README.md docs/Home.md
          cp docs/SUMMARY.md docs/_Sidebar.md
          cp CHANGELOG.md docs/information/changelog.md
      - name: Commit files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'docs: update'
          branch: 'docs/auto-update'
          commit_options: ' --signoff'
          push_options: '--force'
      - name: pull-request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: 'docs/auto-update'
          destination_branch: "master"
          pr_title: "docs: auto-update"
          pr_body: ":crown: *An automated PR*"
          pr_label: "skip-changelog"
      - name: Merge me!
        uses: ridedott/merge-me-action@master
        with:
          GITHUB_LOGIN: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_METHOD: REBASE
```
