### ISSUE TITLE
Question: Commits Fill Up Activity Log

### ISSUE THREAD

**Issue by SudharakaP** [stefanzweifel/git-auto-commit-action#88]
Hi everyone, :smile:  

I have a simple question, I've configured this action to configure small personal repo; https://github.com/SudharakaP/SudharakaP/blob/master/.github/workflows/trivia-update.yml

So every five minutes the action is triggered and for each time a message goes to my activity log and that fills it up, not enabling to see the activity relevant to the people I follow etc. 

![image](https://user-images.githubusercontent.com/12435965/88484958-5ed65380-cf27-11ea-8cd2-8e3b2c1ee486.png)

Is there a way such that this apps commits are not included in the activity log? :thinking:

**Comment by stefanzweifel** [comment]
I'm not aware of a configuration or something to prevent commits from being shown in the activity feed.
However, I assume the activity feed won't show messages for commits which have been made in your name.

The Action can be configured to use different author credentials. If you update both user and author to your name and email address the commits probably won't show up anymore in the feed.
The commits will look like, as if you have created them.

```yaml
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_user_name: Sudharaka Palamakumbura
    commit_user_email: your_email@example.com
    commit_author: Sudharaka Palamakumbura <your_email@example.com>
```
