### ISSUE TITLE
Private repo?

### ISSUE THREAD

**Issue by pvinis** [stefanzweifel/git-auto-commit-action#9]
Hi, I'm trying to use this in a repo that is private. I get this error:
```
remote: Repository not found.
fatal: repository 'https://github.com/ourcompany/ourapp/' not found
##[error]Docker run failed with exit code 128
```

Is there some other setup I need to do?

Right now I have:
```
    - uses: stefanzweifel/git-auto-commit-action@v2.1.0
      with:
        commit_message: Update file
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_BOT_TOKEN }}
```
