### ISSUE TITLE
Custom 'git add' options or just force add

### ISSUE THREAD

**Issue by SeaLoong** [stefanzweifel/git-auto-commit-action#92]
**Is your feature request related to a problem? Please describe.**
I want to generate some files automatically and commit/push them back to my repository(same branch) after push. But the generated files are ignored, because of '.gitignore' file. Git can't track the files,  so that no commit/push.

**Describe the solution you'd like**
If I can custom 'git add' command options, I will add '--force' option to ignore '.gitignore' file.

**Describe alternatives you've considered**
I know I can modify '.gitignore' file to solve my problem, but If I don't ignore the generated files, I must fetch them to local after each push(if the generated files changed).
Just a small function, can you help me?

**Comment by SeaLoong** [comment]
I think my request has some problem, custom  'git add' options can't solve the problem. Maybe I should push files to other branch.

**Comment by alichherawalla** [comment]
for anyone that comes across this at a later point and has a similar use case you can do something like this 
```
- name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_user_name: Gitflow
                  commit_user_email: git@wednesday.is
                  commit_options: '--allow-empty'
                  add_options: '-f'
                  commit_message: 'Created lib'
                  file_pattern: 'lib'
                  disable_globbing: false
                  skip_dirty_check: true
```

the `skip_dirty_check: true` is the trick
