### ISSUE TITLE
How to use environment variables in a commit message?

### ISSUE THREAD

**Issue by thinkh** [stefanzweifel/git-auto-commit-action#94]
I'd like to use the following commit message to print the commit hash from my PR into the commit to the GitHub Pages branch:

```yaml
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: Update files with commit $GITHUB_SHA
    branch: gh-pages
```

Unfortunately, the environment variable `$GITHUB_SHA` is not replaced, even though it is [available by default](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables).

Is there a way to use environment variables in a commit message?

**Comment by stefanzweifel** [comment]
I think the following configuration should work.

```
- uses: stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: Update files with commit ${{ github.sha }}
    branch: gh-pages
```

(I've taken this "example" from here: https://docs.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#example-calling-the-rest-api)

In #89 the entire message had to be dynamic. But I think the `${{ github.sha }}` format should work fine for your usecase.
