### ISSUE TITLE
Autodetect branch breaks on creating orphan

### ISSUE THREAD

**Issue by awushensky** [stefanzweifel/git-auto-commit-action#96]
**Version of the Action**
`v4.5.0`

**Describe the bug**
When `branch` is not specified, this action fails

**To Reproduce**
1. Create a github action which modifies files on master branch
2. attempt to use git-auto-commit-action@v4 to create a commit, do not specify the branch
3. observe the failure

**Expected behavior**
Previous versions correctly identified the master branch.

Specifying `branch: master` resolves this issue, but `branch` is listed as optional in the action description.

**Used Workflow**
```yaml
      - name: create commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic changelog update"
          file_pattern: "gradle.properties CHANGELOG.md"
```

**Github Action Log**
```
Run stefanzweifel/git-auto-commit-action@v4
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
+ _main
+ _switch_to_repository
+ echo 'INPUT_REPOSITORY value: .'
INPUT_REPOSITORY value: .
+ cd .
+ _git_is_dirty
++ git status -s -- gradle.properties CHANGELOG.md
+ '[' -n ' M CHANGELOG.md
 M gradle.properties' ']'
+ echo '::set-output name=changes_detected::true'
+ _switch_to_branch
+ echo 'INPUT_BRANCH value: '
+ git show-ref --verify --quiet refs/heads/
INPUT_BRANCH value: 
+ git checkout --orphan
error: option `orphan' requires a value
Error: Invalid status code: 129
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 129
}
Error: Invalid status code: 129
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
```
