### ISSUE TITLE
insufficient permission for adding an object to repository database .git/objects

### ISSUE THREAD

**Issue by HotelCalifornia** [stefanzweifel/git-auto-commit-action#99]
**Version of the Action**
`v4.x.x`

**Describe the bug**
```
Run stefanzweifel/git-auto-commit-action@v4
  with:
    commit_message: 🎨 apply clang-format changes
    branch: revert-1-update-ci
    file_pattern: .
    repository: .
    commit_user_name: GitHub Actions
    commit_user_email: actions@github.com
    commit_author: HotelCalifornia <HotelCalifornia@users.noreply.github.com>
    skip_dirty_check: false
Started: bash /home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/entrypoint.sh
INPUT_REPOSITORY value: .
INPUT_BRANCH value: revert-1-update-ci
Already on 'revert-1-update-ci'
M	src/main.cpp
Your branch is up to date with 'origin/revert-1-update-ci'.
INPUT_FILE_PATTERN: .
error: insufficient permission for adding an object to repository database .git/objects
error: src/main.cpp: failed to insert into database
error: unable to index file 'src/main.cpp'
fatal: updating files failed
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```
see [purduesigbots/liblvgl#2 workflow result](https://github.com/purduesigbots/liblvgl/pull/2/checks?check_run_id=1106717185)

**To Reproduce**
Run the following workflow

**Used Workflow**

```yaml
name: "format code"

# run on pull requests to develop
on:
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      # check out HEAD on the branch
      - name: checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 2
      # format the latest commit
      - name: format code
        uses: purduesigbots/clang-format-action@main
      # commit the changes
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 🎨 apply clang-format changes
          branch: ${{ github.head_ref }}
```
